/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import controle.ControleCliente;
import entidade.CCliente;
import entidade.CEndereco;
import entidade.ModeloTabela;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import util.ConectaBanco;

/**
 *
 * @author Henike
 */
public class Cliente extends javax.swing.JFrame {

    ConectaBanco conex = ConectaBanco.getInstance();
    CCliente cliente = new CCliente();
    CEndereco endereco = new CEndereco();
    ControleCliente control = new ControleCliente();
    int flag = 0;

    /**
     * Creates new form TelaCadastroCliente
     */
    public Cliente() {
        initComponents();

        try {
            MaskFormatter form = new MaskFormatter("##.###.###-#");
            jFormattedTextFieldRG.setFormatterFactory(new DefaultFormatterFactory(form));
            form = new MaskFormatter("###.###.###-##");
            jFormattedTextFieldCPF.setFormatterFactory(new DefaultFormatterFactory(form));
            form = new MaskFormatter("#####-###");
            jFormattedTextFieldCEP.setFormatterFactory(new DefaultFormatterFactory(form));
        } catch (ParseException ex) {
            Logger.getLogger(Cliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.preencherComboBoxCid();
        this.preencherComboBoxEst(null);
        this.preencherTabela("select * from view_cliente_detalhes order by nome");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jTextFieldRua = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jFormattedTextFieldRG = new javax.swing.JFormattedTextField();
        jFormattedTextFieldCPF = new javax.swing.JFormattedTextField();
        jButtonSalvar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButtonNovo = new javax.swing.JButton();
        jTextFieldNome = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldNum = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jFormattedTextFieldCEP = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldCompl = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jComboBoxCid = new javax.swing.JComboBox();
        jButtonAddCid = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldPesqCli = new javax.swing.JTextField();
        jButtonPesquisar = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldOrgaoExp = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextFieldBairro = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jComboBoxEst = new javax.swing.JComboBox();
        jTextFieldRes = new javax.swing.JTextField();
        jTextFieldCom = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar cliente");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTextFieldRua.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldRua.setEnabled(false);

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabela);

        jFormattedTextFieldRG.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jFormattedTextFieldRG.setEnabled(false);

        jFormattedTextFieldCPF.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jFormattedTextFieldCPF.setEnabled(false);

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setEnabled(false);
        jButtonSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonSalvarMouseEntered(evt);
            }
        });
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.setEnabled(false);
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setEnabled(false);
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Cadastrar cliente");

        jLabel3.setText("Nome:");

        jLabel4.setText("Telefone residencial:");

        jLabel5.setText("Rua:");

        jLabel6.setText("RG:");

        jLabel7.setText("CPF:");

        jButtonNovo.setText("Novo");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });

        jTextFieldNome.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldNome.setEnabled(false);

        jLabel8.setText("Email:");

        jTextFieldEmail.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldEmail.setEnabled(false);

        jLabel9.setText("Número:");

        jTextFieldNum.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldNum.setEnabled(false);

        jLabel10.setText("Cep:");

        jFormattedTextFieldCEP.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jFormattedTextFieldCEP.setEnabled(false);

        jLabel11.setText("Complemento:");

        jTextFieldCompl.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldCompl.setEnabled(false);

        jLabel12.setText("Cidade:");

        jComboBoxCid.setEnabled(false);
        jComboBoxCid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jComboBoxCidMouseEntered(evt);
            }
        });

        jButtonAddCid.setText("+");
        jButtonAddCid.setEnabled(false);
        jButtonAddCid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddCidActionPerformed(evt);
            }
        });

        jLabel14.setText("Telefone comercial:");

        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });

        jLabel15.setText("Orgão Expedidor:");

        jTextFieldOrgaoExp.setEnabled(false);

        jLabel16.setText("Bairro:");

        jTextFieldBairro.setEnabled(false);

        jLabel2.setText("Pesquisar cliente:");

        jLabel13.setText("Estado:");

        jComboBoxEst.setEnabled(false);
        jComboBoxEst.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jComboBoxEstMouseEntered(evt);
            }
        });

        jTextFieldRes.setEnabled(false);

        jTextFieldCom.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldRua, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addComponent(jFormattedTextFieldCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jFormattedTextFieldCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldEmail)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))))
                                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextFieldPesqCli)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButtonPesquisar))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButtonSalvar)
                                        .addGap(29, 29, 29)
                                        .addComponent(jButtonExcluir)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButtonCancelar)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldNum, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jTextFieldRes, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jComboBoxCid, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButtonAddCid, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jFormattedTextFieldRG, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jTextFieldOrgaoExp, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                                                    .addComponent(jLabel15)))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(11, 11, 11)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jComboBoxEst, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel13)
                                                    .addComponent(jTextFieldCompl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                                                    .addComponent(jLabel11)))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(jLabel14))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextFieldCom, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 682, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jButtonNovo)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonSair)))
                            .addComponent(jLabel2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(292, 292, 292)
                        .addComponent(jLabel1)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldOrgaoExp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel14)
                    .addComponent(jLabel7))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextFieldCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCompl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel16)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextFieldCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxCid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAddCid)
                    .addComponent(jComboBoxEst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPesqCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNovo)
                    .addComponent(jButtonSalvar)
                    .addComponent(jButtonExcluir)
                    .addComponent(jButtonCancelar)
                    .addComponent(jButtonSair))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        flag = 1;
        jTextFieldNome.setEnabled(true);
        jTextFieldNome.setText("");
        jFormattedTextFieldRG.setEnabled(true);
        jFormattedTextFieldRG.setText("");
        jTextFieldOrgaoExp.setEnabled(true);
        jTextFieldOrgaoExp.setText("");
        jFormattedTextFieldCPF.setEnabled(true);
        jFormattedTextFieldCPF.setText("");
        jTextFieldEmail.setEnabled(true);
        jTextFieldEmail.setText("");
        jTextFieldRes.setText("");
        jTextFieldRes.setEnabled(true);
        jTextFieldCom.setText("");
        jTextFieldCom.setEnabled(true);
        jTextFieldRua.setEnabled(true);
        jTextFieldRua.setText("");
        jTextFieldNum.setEnabled(true);
        jTextFieldNum.setText("");
        jTextFieldBairro.setEnabled(true);
        jTextFieldBairro.setText("");
        jFormattedTextFieldCEP.setEnabled(true);
        jFormattedTextFieldCEP.setText("");
        jTextFieldCompl.setEnabled(true);
        jTextFieldCompl.setText("");
        jComboBoxCid.setSelectedItem("");
        jComboBoxCid.setEnabled(true);
        jButtonAddCid.setEnabled(true);
        jComboBoxEst.setSelectedItem("");
        jComboBoxEst.setEnabled(true);
        jButtonSalvar.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        jButtonNovo.setEnabled(false);
        jButtonExcluir.setEnabled(false);
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        if (flag == 0) {
            if (JOptionPane.showConfirmDialog(rootPane, "Deseja realmente alterar?", "Confirmar Alteração", JOptionPane.YES_NO_OPTION) == 0) {
                try {
                    cliente.setNome(jTextFieldNome.getText());
                    cliente.setRg(jFormattedTextFieldRG.getText());
                    cliente.setOrgao_expedidor(jTextFieldOrgaoExp.getText());
                    cliente.setCpf(jFormattedTextFieldCPF.getText());
                    cliente.setEmail(jTextFieldEmail.getText());
                    cliente.setTelefone(jTextFieldRes.getText());
                    cliente.setCelular(jTextFieldCom.getText());

                    endereco.setRua(jTextFieldRua.getText());
                    endereco.setNumero(jTextFieldNum.getText());
                    endereco.setBairro(jTextFieldBairro.getText());
                    endereco.setCep(jFormattedTextFieldCEP.getText());
                    endereco.setComplemento(jTextFieldCompl.getText());
                    endereco.setCidade((String) jComboBoxCid.getSelectedItem());
                    endereco.setEstado((String) jComboBoxEst.getSelectedItem());

                    if (control.alterar(cliente, endereco)) {
                        this.estadoInicial();
                        this.preencherTabela("select * from view_cliente_detalhes order by nome");
                    }
                } catch (NumberFormatException ex) {
                    JOptionPane.showMessageDialog(null, "Erro ao alterar o cliente!\nERROR: Número de endereço inválido.");
                }
            }
        } else {
            try {
                cliente.setNome(jTextFieldNome.getText());
                cliente.setRg(jFormattedTextFieldRG.getText());
                cliente.setOrgao_expedidor(jTextFieldOrgaoExp.getText());
                cliente.setCpf(jFormattedTextFieldCPF.getText());
                cliente.setEmail(jTextFieldEmail.getText());
                cliente.setTelefone(jTextFieldRes.getText());
                cliente.setCelular(jTextFieldCom.getText());

                endereco.setRua(jTextFieldRua.getText());
                endereco.setNumero(jTextFieldNum.getText());
                endereco.setBairro(jTextFieldBairro.getText());
                endereco.setCep(jFormattedTextFieldCEP.getText());
                endereco.setComplemento(jTextFieldCompl.getText());
                endereco.setCidade((String) jComboBoxCid.getSelectedItem());
                endereco.setEstado((String) jComboBoxEst.getSelectedItem());

                if (control.salvar(cliente, endereco)) {
                    this.estadoInicial();
                    this.preencherTabela("select * from view_cliente_detalhes order by nome");
                    flag = 0;
                }
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "Erro ao inserir o cliente!\nERROR: Número de endereço inválido.");
            }
        }
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        if (JOptionPane.showConfirmDialog(rootPane, "Deseja realmente excluir?", "Confirmar Exclusão", JOptionPane.YES_NO_OPTION) == 0) {
            cliente.setNome(jTextFieldNome.getText());
            cliente.setRg(jFormattedTextFieldRG.getText());
            cliente.setOrgao_expedidor(jTextFieldOrgaoExp.getText());
            cliente.setCpf(jFormattedTextFieldCPF.getText());
            cliente.setEmail(jTextFieldEmail.getText());
            cliente.setTelefone(jTextFieldRes.getText());
            cliente.setCelular(jTextFieldCom.getText());
            // por o endereco
            endereco.setRua(jTextFieldRua.getText());
            endereco.setNumero(jTextFieldNum.getText());
            endereco.setBairro(jTextFieldBairro.getText());
            endereco.setCep(jFormattedTextFieldCEP.getText());
            endereco.setComplemento(jTextFieldCompl.getText());
            endereco.setCidade((String) jComboBoxCid.getSelectedItem());
            endereco.setEstado((String) jComboBoxEst.getSelectedItem());

            control.excluir(cliente, endereco);
            this.estadoInicial();
            this.preencherTabela("select * from view_cliente_detalhes order by nome");
        }
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        this.estadoInicial();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        this.preencherTabela("select * from view_cliente_detalhes where nome ~* '" + jTextFieldPesqCli.getText() + "' order by nome");
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        // não pode ser ativada quando o botão novo for acionado!!!!! 
        if (flag == 0) {
            String nome = "" + tabela.getValueAt(tabela.getSelectedRow(), 0);
            conex.conexao();
            conex.executaSQL("select * from view_cliente_detalhes where nome='" + nome + "'");
            try {
                conex.rs.first();
                cliente.setCodc(conex.rs.getInt("codc"));
                jTextFieldNome.setText(String.valueOf(conex.rs.getString("nome")));
                jTextFieldRes.setText(String.valueOf(conex.rs.getString("numero_tel")));
                jTextFieldCom.setText(String.valueOf(conex.rs.getString("numero_cel")));
                jFormattedTextFieldRG.setText(String.valueOf(conex.rs.getString("rg")));
                jTextFieldOrgaoExp.setText(String.valueOf(conex.rs.getString("orgao_expedidor")));
                jFormattedTextFieldCPF.setText(String.valueOf(conex.rs.getString("cpf")));
                jTextFieldEmail.setText(String.valueOf(conex.rs.getString("email")));
                //endereco.setCode(conex.rs.getInt("code"));
                jTextFieldRua.setText(String.valueOf(conex.rs.getString("rua")));
                jTextFieldNum.setText(String.valueOf(conex.rs.getInt("numero")));
                jTextFieldBairro.setText(String.valueOf(conex.rs.getString("bairro")));
                jFormattedTextFieldCEP.setText(String.valueOf(conex.rs.getString("cep")));
                jTextFieldCompl.setText(String.valueOf(conex.rs.getString("complemento")));
                jComboBoxCid.setSelectedItem(String.valueOf(conex.rs.getString("nome_cidade")));
                jComboBoxEst.setSelectedItem(String.valueOf(conex.rs.getString("uf")));
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Erro ao selecionar os dados!\n" + ex.getMessage());
            }
            conex.desconecta();

            jTextFieldNome.setEnabled(true);
            jFormattedTextFieldRG.setEnabled(true);
            jTextFieldOrgaoExp.setEnabled(true);
            jFormattedTextFieldCPF.setEnabled(true);
            jTextFieldEmail.setEnabled(true);
            jTextFieldRes.setEnabled(true);
            jTextFieldCom.setEnabled(true);
            jTextFieldRua.setEnabled(true);
            jTextFieldNum.setEnabled(true);
            jTextFieldBairro.setEnabled(true);
            jFormattedTextFieldCEP.setEnabled(true);
            jTextFieldCompl.setEnabled(true);
            jComboBoxCid.setEnabled(true);
            jButtonAddCid.setEnabled(true);
            jComboBoxEst.setEnabled(true);
            jButtonNovo.setEnabled(false);
            jButtonSalvar.setEnabled(true);
            jButtonExcluir.setEnabled(true);
            jButtonCancelar.setEnabled(true);
        }
    }//GEN-LAST:event_tabelaMouseClicked

    private void jButtonAddCidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddCidActionPerformed
        new TelaCadastroCidade().setVisible(true);
    }//GEN-LAST:event_jButtonAddCidActionPerformed

    private void jComboBoxEstMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxEstMouseEntered
        this.preencherComboBoxEst((String) jComboBoxCid.getSelectedItem());
    }//GEN-LAST:event_jComboBoxEstMouseEntered

    private void jComboBoxCidMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxCidMouseEntered
        this.preencherComboBoxCid();
        this.preencherComboBoxEst((String) jComboBoxCid.getSelectedItem());
    }//GEN-LAST:event_jComboBoxCidMouseEntered

    private void jButtonSalvarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSalvarMouseEntered
        this.preencherComboBoxEst((String) jComboBoxCid.getSelectedItem());
    }//GEN-LAST:event_jButtonSalvarMouseEntered

    private void preencherComboBoxCid() {
        conex.conexao();
        conex.executaSQL("select distinct nome from cidade order by nome");
        Object obj = jComboBoxCid.getSelectedItem();
        jComboBoxCid.removeAllItems();
        jComboBoxCid.addItem("");
        try {
            conex.rs.first();
            do {
                jComboBoxCid.addItem(conex.rs.getString("nome"));
            } while (conex.rs.next());
        } catch (SQLException ex) {
            //JOptionPane.showMessageDialog(rootPane, "Erro ao preencher combo box!\n"+ex.getMessage());
        }
        jComboBoxCid.setSelectedItem(obj);
        conex.desconecta();
    }

    private void preencherComboBoxEst(String cidade) {
        conex.conexao();

        if (cidade == null) {
            conex.executaSQL("select * from estado");
        } else {
            conex.executaSQL("select * from cidade where nome='" + cidade + "' order by uf");
        }

        Object obj = jComboBoxEst.getSelectedItem();
        jComboBoxEst.removeAllItems();
        jComboBoxEst.addItem("");
        try {
            conex.rs.first();
            do {
                jComboBoxEst.addItem(conex.rs.getString("uf"));
            } while (conex.rs.next());
        } catch (SQLException ex) {
            //JOptionPane.showMessageDialog(rootPane, "Erro ao preencher combo box!\n"+ex.getMessage());
        }
        jComboBoxEst.setSelectedItem(obj);
        conex.desconecta();
    }

    private void preencherTabela(String sql) {
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"Nome", "CPF", "CEP", "Telefone", "Telefone"};
        int i = 0;
        conex.conexao();
        conex.executaSQL(sql);
        try {
            conex.rs.first();
            do {
                i++;
                dados.add(new Object[]{conex.rs.getString("nome"), conex.rs.getString("cpf"),
                    conex.rs.getString("cep"), conex.rs.getString("numero_tel"), conex.rs.getString("numero_cel")});
            } while (conex.rs.next());
        } catch (SQLException ex) {
            //JOptionPane.showMessageDialog(this, "Erro ao preencher Arraylist!\n"+ex.getMessage());
        }

        ModeloTabela modelotabela = new ModeloTabela(dados, colunas);
        tabela.setModel(modelotabela);
        if (i > 5) {
            tabela.getColumnModel().getColumn(0).setPreferredWidth(133);
            tabela.getColumnModel().getColumn(1).setPreferredWidth(132);
            tabela.getColumnModel().getColumn(2).setPreferredWidth(132);
            tabela.getColumnModel().getColumn(3).setPreferredWidth(132);
            tabela.getColumnModel().getColumn(4).setPreferredWidth(132);
        } else {
            tabela.getColumnModel().getColumn(0).setPreferredWidth(136);
            tabela.getColumnModel().getColumn(1).setPreferredWidth(135);
            tabela.getColumnModel().getColumn(2).setPreferredWidth(135);
            tabela.getColumnModel().getColumn(3).setPreferredWidth(135);
            tabela.getColumnModel().getColumn(4).setPreferredWidth(135);
        }
        tabela.getColumnModel().getColumn(0).setResizable(false);
        tabela.getColumnModel().getColumn(1).setResizable(false);
        tabela.getColumnModel().getColumn(2).setResizable(false);
        tabela.getColumnModel().getColumn(3).setResizable(false);
        tabela.getColumnModel().getColumn(4).setResizable(false);
        tabela.getTableHeader().setReorderingAllowed(false);
        tabela.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tabela.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        conex.desconecta();
    }

    private void estadoInicial() {
        flag = 0;
        jTextFieldNome.setText("");
        jFormattedTextFieldRG.setText("");
        jTextFieldOrgaoExp.setText("");
        jFormattedTextFieldCPF.setText("");
        jTextFieldEmail.setText("");
        jTextFieldRua.setText("");
        jTextFieldNum.setText("");
        jTextFieldBairro.setText("");
        jFormattedTextFieldCEP.setText("");
        jTextFieldCompl.setText("");
        jTextFieldRes.setText("");
        jTextFieldCom.setText("");
        jComboBoxCid.setSelectedItem("");
        this.preencherComboBoxEst(null);
        jComboBoxEst.setSelectedItem("");
        jTextFieldNome.setEnabled(!true);
        jFormattedTextFieldRG.setEnabled(!true);
        jTextFieldOrgaoExp.setEnabled(!true);
        jFormattedTextFieldCPF.setEnabled(!true);
        jTextFieldEmail.setEnabled(!true);
        jTextFieldRes.setEnabled(!true);
        jTextFieldCom.setEnabled(!true);
        jTextFieldRua.setEnabled(!true);
        jTextFieldNum.setEnabled(!true);
        jTextFieldBairro.setEnabled(!true);
        jFormattedTextFieldCEP.setEnabled(!true);
        jTextFieldCompl.setEnabled(!true);
        jComboBoxCid.setEnabled(!true);
        jButtonAddCid.setEnabled(!true);
        jComboBoxEst.setEnabled(!true);
        jButtonSalvar.setEnabled(!true);
        jButtonCancelar.setEnabled(!true);
        jButtonNovo.setEnabled(!false);
        jButtonExcluir.setEnabled(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Cliente().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddCid;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox jComboBoxCid;
    private javax.swing.JComboBox jComboBoxEst;
    private javax.swing.JFormattedTextField jFormattedTextFieldCEP;
    private javax.swing.JFormattedTextField jFormattedTextFieldCPF;
    private javax.swing.JFormattedTextField jFormattedTextFieldRG;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldBairro;
    private javax.swing.JTextField jTextFieldCom;
    private javax.swing.JTextField jTextFieldCompl;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldNum;
    private javax.swing.JTextField jTextFieldOrgaoExp;
    private javax.swing.JTextField jTextFieldPesqCli;
    private javax.swing.JTextField jTextFieldRes;
    private javax.swing.JTextField jTextFieldRua;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
