/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import controle.ControleProduto;
import entidade.CProduto;
import entidade.ModeloTabela;
import java.math.BigDecimal;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.text.MaskFormatter;
import util.ConectaBanco;

/**
 *
 * @author Henike
 */
public class Produto extends javax.swing.JFrame {

    ConectaBanco conex = ConectaBanco.getInstance();
    //ConectaBancoSingleton conexPesq = ConectaBancoSingleton.getInstance();
    CProduto produto = new CProduto();
    ControleProduto control = new ControleProduto();
    int flag = 0;

    /**
     * Creates new form TelaCadastroProduto
     */
    public Produto() {
        initComponents();

        SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        Date hoje = new Date();
        jFormattedTextFieldData.setText(df.format(hoje));

        try {
            MaskFormatter form = new MaskFormatter("##/##/####");
        } catch (ParseException ex) {
            Logger.getLogger(TelaCadastroTelefone.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.preencherComboForn();
        this.preencherComboCat();
        this.preencherTabela("select distinct * from view_produtos_recentes_detalhes order by nome");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldProduto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldQtde = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxForn = new javax.swing.JComboBox();
        jButtonNovo = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jTextFieldPesqProd = new javax.swing.JTextField();
        jButtonPesquisar = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jTextFieldPrecoComp = new javax.swing.JTextField();
        jTextFieldPrecoVenda = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jFormattedTextFieldData = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldCodBar = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldLucro = new javax.swing.JTextField();
        jTextFieldEstMin = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jComboBoxCat = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar produto");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Cadastrar produto");

        jLabel3.setText("Produto:");

        jTextFieldProduto.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldProduto.setEnabled(false);

        jLabel4.setText("Quantidade:");

        jTextFieldQtde.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldQtde.setEnabled(false);

        jLabel5.setText("Preço de Compra R$:");

        jLabel6.setText("Preço de Venda R$:");

        jLabel7.setText("Fornecedor:");

        jComboBoxForn.setEnabled(false);
        jComboBoxForn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jComboBoxFornMouseEntered(evt);
            }
        });

        jButtonNovo.setText("Novo");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setEnabled(false);
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.setEnabled(false);
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setEnabled(false);
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });

        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela);

        jTextFieldPrecoComp.setEnabled(false);

        jTextFieldPrecoVenda.setEnabled(false);

        jLabel9.setText("Data:");

        jFormattedTextFieldData.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jFormattedTextFieldData.setEnabled(false);

        jLabel10.setText("Código de barras:");

        jTextFieldCodBar.setEnabled(false);

        jLabel11.setText("Estoque mínimo:");

        jLabel12.setText("Lucro R$:");

        jTextFieldLucro.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldLucro.setEnabled(false);

        jTextFieldEstMin.setEnabled(false);

        jLabel8.setText("Categoria:");

        jComboBoxCat.setEnabled(false);
        jComboBoxCat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jComboBoxCatMouseEntered(evt);
            }
        });

        jLabel2.setText("Pesquisar produto:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(221, 221, 221))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonNovo)
                                .addGap(20, 20, 20)
                                .addComponent(jButtonSalvar))
                            .addComponent(jLabel10)
                            .addComponent(jTextFieldCodBar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonExcluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 309, Short.MAX_VALUE))
                            .addComponent(jTextFieldProduto)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addComponent(jComboBoxForn, javax.swing.GroupLayout.Alignment.TRAILING, 0, 140, Short.MAX_VALUE)
                                    .addComponent(jTextFieldPrecoVenda, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addComponent(jTextFieldQtde, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(26, 26, 26)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(0, 85, Short.MAX_VALUE)
                                            .addComponent(jButtonCancelar)
                                            .addGap(24, 24, 24))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jComboBoxCat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextFieldPrecoComp, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(24, 24, 24)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jTextFieldEstMin, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(24, 24, 24)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextFieldLucro)
                                .addComponent(jFormattedTextFieldData, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel9)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                                            .addComponent(jTextFieldPesqProd))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonPesquisar))
                                    .addComponent(jButtonSair, javax.swing.GroupLayout.Alignment.TRAILING))))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCodBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel11)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldQtde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldEstMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldLucro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPrecoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPrecoComp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxForn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPesqProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNovo)
                    .addComponent(jButtonSalvar)
                    .addComponent(jButtonExcluir)
                    .addComponent(jButtonCancelar)
                    .addComponent(jButtonSair))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(654, 550));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        if (flag == 0) {
            if (JOptionPane.showConfirmDialog(rootPane, "Deseja realmente alterar?", "Confirmar Alteração", JOptionPane.YES_NO_OPTION) == 0) {
                try {
                    //produto.setCodp(Integer.parseInt(jTextFieldCod.getText()));
                    produto.setCod_barras(jTextFieldCodBar.getText());
                    produto.setNome(jTextFieldProduto.getText());
                    produto.setQuantidade(Integer.parseInt(jTextFieldQtde.getText()));
                    produto.setEstoque_minimo(Integer.parseInt(jTextFieldEstMin.getText()));
                    String precoComp = jTextFieldPrecoComp.getText().replace(",", ".");
                    String precoVenda = jTextFieldPrecoVenda.getText().replace(",", ".");
                    produto.setPreco_compra(Float.parseFloat(precoComp));
                    produto.setPreco_venda(Float.parseFloat(precoVenda));
                    produto.setData(jFormattedTextFieldData.getText());
                    produto.setFornecedor((String) jComboBoxForn.getSelectedItem());
                    produto.setCategoria((String) jComboBoxCat.getSelectedItem());

                    if (control.alterar(produto)) {
                        this.estadoInicial();
                        this.preencherTabela("select distinct * from view_produtos_recentes_detalhes order by nome");
                    }
                } catch (NumberFormatException ex) {
                    JOptionPane.showMessageDialog(this, "Formato de número inválido!\n" + ex.getMessage());
                }
            }
        } else {
            try {
                produto.setCod_barras(jTextFieldCodBar.getText());
                produto.setNome(jTextFieldProduto.getText());
                produto.setQuantidade(Integer.parseInt(jTextFieldQtde.getText()));
                produto.setEstoque_minimo(Integer.parseInt(jTextFieldEstMin.getText()));
                String precoComp = jTextFieldPrecoComp.getText().replace(",", ".");
                String precoVenda = jTextFieldPrecoVenda.getText().replace(",", ".");
                produto.setPreco_compra(Float.parseFloat(precoComp));
                produto.setPreco_venda(Float.parseFloat(precoVenda));
                produto.setData(jFormattedTextFieldData.getText());
                produto.setFornecedor((String) jComboBoxForn.getSelectedItem());
                produto.setCategoria((String) jComboBoxCat.getSelectedItem());

                if (control.inserir(produto)) {
                    this.estadoInicial();
                    this.preencherTabela("select distinct * from view_produtos_recentes_detalhes order by nome");
                    flag = 0;
                }
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Formato de número inválido!\n" + ex.getMessage());
            }
        }
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        flag = 1;
        jTextFieldCodBar.setEnabled(true);
        jTextFieldProduto.setEnabled(true);
        jTextFieldQtde.setEnabled(true);
        jTextFieldEstMin.setEnabled(true);
        jTextFieldPrecoComp.setEnabled(true);
        jTextFieldPrecoVenda.setEnabled(true);
        //jTextFieldCod.setText("");
        jTextFieldCodBar.setText("");
        jTextFieldProduto.setText("");
        jTextFieldQtde.setText("");
        jTextFieldEstMin.setText("");
        jTextFieldLucro.setText("");
        jTextFieldPrecoComp.setText("");
        jTextFieldPrecoVenda.setText("");
        jComboBoxForn.setSelectedItem("");
        jComboBoxForn.setEnabled(true);
        jComboBoxCat.setSelectedItem("");
        jComboBoxCat.setEnabled(true);
        jTextFieldPesqProd.setText("");
        jButtonSalvar.setEnabled(true);
        jButtonNovo.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        jButtonCancelar.setEnabled(true);
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        this.preencherTabela("select distinct * from view_produtos_recentes_detalhes where nome ~* '" + jTextFieldPesqProd.getText() + "' order by nome");
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        if (JOptionPane.showConfirmDialog(rootPane, "Deseja realmente excluir?", "Confirmar Exclusão", JOptionPane.YES_NO_OPTION) == 0) {
            //produto.setCodp(Integer.parseInt(jTextFieldCod.getText()));
            produto.setCod_barras(jTextFieldCodBar.getText());
            produto.setNome(jTextFieldProduto.getText());
            produto.setQuantidade(Integer.parseInt(jTextFieldQtde.getText()));
            produto.setEstoque_minimo(Integer.parseInt(jTextFieldEstMin.getText()));
            String precoComp = jTextFieldPrecoComp.getText().replace(",", ".");
            String precoVenda = jTextFieldPrecoVenda.getText().replace(",", ".");
            produto.setPreco_compra(Float.parseFloat(precoComp));
            produto.setPreco_venda(Float.parseFloat(precoVenda));
            produto.setData(jFormattedTextFieldData.getText());
            produto.setFornecedor((String) jComboBoxForn.getSelectedItem());
            produto.setCategoria((String) jComboBoxCat.getSelectedItem());

            control.excluir(produto);
            this.estadoInicial();
            this.preencherTabela("select distinct * from view_produtos_recentes_detalhes order by nome");
        }
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        this.estadoInicial();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        // não pode ser ativada quando o botão novo for acionado!!!!! 
        if (flag == 0) {
            String nomeProd = "" + tabela.getValueAt(tabela.getSelectedRow(), 0);
            conex.conexao();
            conex.executaSQL("select * from view_produtos_recentes_detalhes where nome='" + nomeProd + "'");
            try {
                conex.rs.first();
                int codf = conex.rs.getInt("codf");
                int codcat = conex.rs.getInt("codcat");
                produto.setCodp(conex.rs.getInt("codp"));
                //jTextFieldCod.setText(String.valueOf(conex.rs.getInt("codp")));
                jTextFieldCodBar.setText(conex.rs.getString("cod_barras"));
                jTextFieldProduto.setText(conex.rs.getString("nome"));
                jTextFieldEstMin.setText(String.valueOf(conex.rs.getInt("estoque_minimo")));
                BigDecimal lucro = new BigDecimal(conex.rs.getFloat("preco_venda") - conex.rs.getFloat("preco_compra")).setScale(2, BigDecimal.ROUND_HALF_UP);
                jTextFieldLucro.setText(String.valueOf(lucro));
                jTextFieldPrecoComp.setText(String.valueOf(conex.rs.getBigDecimal("preco_compra")));
                jTextFieldPrecoVenda.setText(String.valueOf(conex.rs.getBigDecimal("preco_venda")));
                jTextFieldQtde.setText(String.valueOf(conex.rs.getInt("quantidade")));

                conex.executaSQL("select * from fornecedor where codf=" + codf);
                conex.rs.first();
                jComboBoxForn.setSelectedItem(conex.rs.getString("nome"));

                conex.executaSQL("select * from categoria where codcat=" + codcat);
                conex.rs.first();
                jComboBoxCat.setSelectedItem(conex.rs.getString("nome"));
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Erro ao selecionar os dados!\n" + ex.getMessage());
            }
            conex.desconecta();
            jTextFieldCodBar.setEnabled(true);
            jTextFieldProduto.setEnabled(true);
            jTextFieldQtde.setEnabled(true);
            jTextFieldEstMin.setEnabled(true);
            jTextFieldPrecoComp.setEnabled(true);
            jTextFieldPrecoVenda.setEnabled(true);
            jComboBoxForn.setEnabled(true);
            jComboBoxCat.setEnabled(true);
            jButtonNovo.setEnabled(false);
            jButtonSalvar.setEnabled(true);
            jButtonExcluir.setEnabled(true);
            jButtonCancelar.setEnabled(true);
        }
    }//GEN-LAST:event_tabelaMouseClicked

    private void jComboBoxFornMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxFornMouseEntered
        this.preencherComboForn();
    }//GEN-LAST:event_jComboBoxFornMouseEntered

    private void jComboBoxCatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxCatMouseEntered
        this.preencherComboCat();
    }//GEN-LAST:event_jComboBoxCatMouseEntered

    private void preencherComboForn() {
        conex.conexao();
        conex.executaSQL("select * from fornecedor order by nome");
        Object obj = jComboBoxForn.getSelectedItem();
        jComboBoxForn.removeAllItems();
        jComboBoxForn.addItem("");
        try {
            conex.rs.first();
            do {
                jComboBoxForn.addItem(conex.rs.getString("nome"));
            } while (conex.rs.next());
        } catch (SQLException ex) {
            //JOptionPane.showMessageDialog(this, "Erro ao preencher combobox!\n"+ex.getMessage());
        }
        jComboBoxForn.setSelectedItem(obj);
        conex.desconecta();
    }

    private void preencherComboCat() {
        conex.conexao();
        conex.executaSQL("select * from categoria order by nome");
        Object obj = jComboBoxCat.getSelectedItem();
        jComboBoxCat.removeAllItems();
        jComboBoxCat.addItem("");
        try {
            conex.rs.first();
            do {
                jComboBoxCat.addItem(conex.rs.getString("nome"));
            } while (conex.rs.next());
        } catch (SQLException ex) {
            //JOptionPane.showMessageDialog(this, "Erro ao preencher combobox!\n"+ex.getMessage());
        }
        jComboBoxCat.setSelectedItem(obj);
        conex.desconecta();
    }

    private void preencherTabela(String sql) {
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"Nome produto", "Preço de venda R$", "Preço de compra R$", "Quantidade"};
        int i = 0;
        conex.conexao();
        try {
            conex.executaSQL(sql);
            conex.rs.first();
            do {
                i++;
                dados.add(new Object[]{conex.rs.getString("nome"), conex.rs.getBigDecimal("preco_venda"),
                    conex.rs.getBigDecimal("preco_compra"), conex.rs.getInt("quantidade")});
            } while (conex.rs.next());
        } catch (SQLException ex) {
            //JOptionPane.showMessageDialog(this, "Erro ao preencher Arraylist!\n"+ex.getMessage());
        }

        ModeloTabela modelotabela = new ModeloTabela(dados, colunas);
        tabela.setModel(modelotabela);
        if (i > 5) {
            tabela.getColumnModel().getColumn(0).setPreferredWidth(132);
            tabela.getColumnModel().getColumn(1).setPreferredWidth(132);
            tabela.getColumnModel().getColumn(2).setPreferredWidth(132);
            tabela.getColumnModel().getColumn(3).setPreferredWidth(132);
        } else {
            tabela.getColumnModel().getColumn(0).setPreferredWidth(136);
            tabela.getColumnModel().getColumn(1).setPreferredWidth(136);
            tabela.getColumnModel().getColumn(2).setPreferredWidth(136);
            tabela.getColumnModel().getColumn(3).setPreferredWidth(135);
        }
        tabela.getColumnModel().getColumn(0).setResizable(false);
        tabela.getColumnModel().getColumn(1).setResizable(false);
        tabela.getColumnModel().getColumn(2).setResizable(false);
        tabela.getColumnModel().getColumn(3).setResizable(false);
        tabela.getTableHeader().setReorderingAllowed(false);
        tabela.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tabela.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        conex.desconecta();
    }

    private void estadoInicial() {
        flag = 0;
        jTextFieldCodBar.setEnabled(false);
        jTextFieldProduto.setEnabled(false);
        jTextFieldQtde.setEnabled(false);
        jTextFieldEstMin.setEnabled(false);
        jTextFieldPrecoComp.setEnabled(false);
        jTextFieldPrecoVenda.setEnabled(false);
        jComboBoxForn.setEnabled(false);
        jComboBoxCat.setEnabled(false);
        //jTextFieldCod.setText("");
        jTextFieldCodBar.setText("");
        jTextFieldProduto.setText("");
        jTextFieldQtde.setText("");
        jTextFieldEstMin.setText("");
        jTextFieldLucro.setText("");
        jTextFieldPrecoComp.setText("");
        jTextFieldPrecoVenda.setText("");
        jTextFieldPesqProd.setText("");
        jComboBoxForn.setSelectedItem("");
        jComboBoxCat.setSelectedItem("");
        jButtonNovo.setEnabled(true);
        jButtonSalvar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        jButtonCancelar.setEnabled(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Produto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Produto().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox jComboBoxCat;
    private javax.swing.JComboBox jComboBoxForn;
    private javax.swing.JFormattedTextField jFormattedTextFieldData;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldCodBar;
    private javax.swing.JTextField jTextFieldEstMin;
    private javax.swing.JTextField jTextFieldLucro;
    private javax.swing.JTextField jTextFieldPesqProd;
    private javax.swing.JTextField jTextFieldPrecoComp;
    private javax.swing.JTextField jTextFieldPrecoVenda;
    private javax.swing.JTextField jTextFieldProduto;
    private javax.swing.JTextField jTextFieldQtde;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
