/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import entidade.ModeloTabela;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import util.ConectaBanco;

/**
 *
 * @author Henike
 */
public class TelaParcelamentoVenda extends javax.swing.JFrame {

    ConectaBanco conex = ConectaBanco.getInstance();
    int codv, flag = 0;

    /**
     * Creates new form TelaPesquisaVenda
     */
    public TelaParcelamentoVenda() {
        initComponents();
        getRootPane().setDefaultButton(jButtonEfetuarPag);

        MaskFormatter formdiaini, formdiafim, formhoraini, formhorafim;
        try {
            formdiaini = new MaskFormatter("##/##/####");
            formdiafim = new MaskFormatter("##/##/####");
            formhoraini = new MaskFormatter("##:##");
            formhorafim = new MaskFormatter("##:##");
            jFormattedTextFieldDataIni.setFormatterFactory(new DefaultFormatterFactory(formdiaini));
            jFormattedTextFieldDataFim.setFormatterFactory(new DefaultFormatterFactory(formdiafim));
            jFormattedTextFieldHoraIni.setFormatterFactory(new DefaultFormatterFactory(formhoraini));
            jFormattedTextFieldHoraFim.setFormatterFactory(new DefaultFormatterFactory(formhorafim));

            // pega data do sistema
            SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
            java.util.Date hoje = new java.util.Date();
            jFormattedTextFieldDataIni.setText(df.format(hoje));
            jFormattedTextFieldDataFim.setText(df.format(hoje));
            jFormattedTextFieldHoraIni.setText("00:00");
            jFormattedTextFieldHoraFim.setText("23:59");
        } catch (ParseException ex) {
            Logger.getLogger(TelaParcelamentoVenda.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonPesquisar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaParcelasVenda = new javax.swing.JTable();
        jFormattedTextFieldDataIni = new javax.swing.JFormattedTextField();
        jFormattedTextFieldDataFim = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jFormattedTextFieldHoraIni = new javax.swing.JFormattedTextField();
        jFormattedTextFieldHoraFim = new javax.swing.JFormattedTextField();
        jButtonAjuda = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jRadioButtonCliente = new javax.swing.JRadioButton();
        jRadioButtonCodVenda = new javax.swing.JRadioButton();
        jRadioButtonDataHoraVenda = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldPesquisa = new javax.swing.JTextField();
        jButtonEfetuarPag = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Vendas Parceladas");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Vendas Parceladas");

        jLabel2.setText("Data inicial:");

        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });

        jLabel3.setText("Vendas parceladas:");

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tabelaMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tabela);

        jLabel4.setText("Parcelas da venda:");

        tabelaParcelasVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabelaParcelasVenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaParcelasVendaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelaParcelasVenda);

        jFormattedTextFieldDataIni.setEnabled(false);

        jFormattedTextFieldDataFim.setEnabled(false);

        jLabel5.setText("Data final:");

        jLabel6.setText("Hora inicial:");

        jLabel7.setText("Hora final:");

        jFormattedTextFieldHoraIni.setEnabled(false);

        jFormattedTextFieldHoraFim.setEnabled(false);

        jButtonAjuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telas/help.gif"))); // NOI18N
        jButtonAjuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAjudaActionPerformed(evt);
            }
        });

        jLabel8.setText("Pesquisar por:");

        buttonGroup1.add(jRadioButtonCliente);
        jRadioButtonCliente.setText("Cliente");
        jRadioButtonCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonClienteMouseClicked(evt);
            }
        });
        jRadioButtonCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonClienteActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonCodVenda);
        jRadioButtonCodVenda.setText("Código da Venda");
        jRadioButtonCodVenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonCodVendaMouseClicked(evt);
            }
        });
        jRadioButtonCodVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCodVendaActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonDataHoraVenda);
        jRadioButtonDataHoraVenda.setText("Período");
        jRadioButtonDataHoraVenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonDataHoraVendaMouseClicked(evt);
            }
        });
        jRadioButtonDataHoraVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonDataHoraVendaActionPerformed(evt);
            }
        });

        jLabel9.setText("Pesquisa:");

        jButtonEfetuarPag.setText("Efetuar Pagamento");
        jButtonEfetuarPag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEfetuarPagActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jRadioButtonCliente)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonCodVenda)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonDataHoraVenda))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(81, 81, 81)
                                .addComponent(jButtonAjuda))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonEfetuarPag)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonCancelar))
                            .addComponent(jScrollPane2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel6))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jFormattedTextFieldHoraIni, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jFormattedTextFieldDataIni, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(41, 41, 41)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel7))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jFormattedTextFieldDataFim)
                                            .addComponent(jFormattedTextFieldHoraFim)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButtonPesquisar)
                                        .addGap(0, 0, Short.MAX_VALUE)))))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(jLabel8)
                                .addGap(6, 6, 6))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButtonCliente)
                            .addComponent(jRadioButtonCodVenda)
                            .addComponent(jRadioButtonDataHoraVenda)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonAjuda)))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jFormattedTextFieldDataIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jFormattedTextFieldHoraFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldHoraIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonCancelar)
                    .addComponent(jButtonEfetuarPag))
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        try {
            SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
            format.setLenient(false);
            Date dataIni = new Date(format.parse(jFormattedTextFieldDataIni.getText()).getTime());
            Date dataFim = new Date(format.parse(jFormattedTextFieldDataFim.getText()).getTime());

            this.preencherTabelaParcelas("select * from view_venda_parcelada where codpr=0");

            if (jRadioButtonDataHoraVenda.isSelected()) {
                this.preencherTabela("select * from view_venda_detalhes "
                        + "where tipo='À prazo' and data between '" + dataIni + "' and '" + dataFim + "' "
                        + "and hora between '" + jFormattedTextFieldHoraIni.getText() + "' and '" + jFormattedTextFieldHoraFim.getText() + "' "
                        + " order by codv");
            } else if (jRadioButtonCodVenda.isSelected()) {
                if (!jTextFieldPesquisa.getText().equals("")) {
                    this.preencherTabela("select * from view_venda_detalhes "
                            + "where tipo='À prazo' and codv=" + jTextFieldPesquisa.getText()
                            + " order by codv");
                } else {
                    this.preencherTabela("select * from view_venda_detalhes "
                            + "where tipo='À prazo' and codv=0"
                            + " order by codv");
                }
            } else if (jRadioButtonCliente.isSelected()) {
                if (jTextFieldPesquisa.getText().equals("")) {
                    this.preencherTabela("select * from view_venda_detalhes where tipo='À prazo' order by codv limit 100");
                } else {
                    this.preencherTabela("select * from view_venda_detalhes "
                            + "where tipo='À prazo' and nome_cliente ~* '" + jTextFieldPesquisa.getText() + "' "
                            + " order by codv");
                }
            }
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, "Data ou hora inválida!");
            //Logger.getLogger(TelaPesquisaVenda.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        int codVenda = (int) tabela.getValueAt(tabela.getSelectedRow(), 0);
        this.preencherTabelaParcelas("select * from view_venda_parcelada where codv =" + codVenda + " order by num_parcela");
    }//GEN-LAST:event_tabelaMouseClicked

    private void jRadioButtonClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonClienteMouseClicked
        flag = 0;
        this.preencherTabela("select * from view_venda_detalhes where codv=0");
        this.preencherTabelaParcelas("select * from view_venda_parcelada where codpr=0");
        jTextFieldPesquisa.setEnabled(true);
        jFormattedTextFieldDataIni.setEnabled(false);
        jFormattedTextFieldDataFim.setEnabled(false);
        jFormattedTextFieldHoraIni.setEnabled(false);
        jFormattedTextFieldHoraFim.setEnabled(false);
    }//GEN-LAST:event_jRadioButtonClienteMouseClicked

    private void jRadioButtonCodVendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonCodVendaMouseClicked
        flag = 0;
        this.preencherTabela("select * from view_venda_detalhes where codv=0");
        this.preencherTabelaParcelas("select * from view_venda_parcelada where codpr=0");
        jTextFieldPesquisa.setEnabled(true);
        jFormattedTextFieldDataIni.setEnabled(false);
        jFormattedTextFieldDataFim.setEnabled(false);
        jFormattedTextFieldHoraIni.setEnabled(false);
        jFormattedTextFieldHoraFim.setEnabled(false);
    }//GEN-LAST:event_jRadioButtonCodVendaMouseClicked

    private void jRadioButtonDataHoraVendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonDataHoraVendaMouseClicked
        flag = 0;
        this.preencherTabela("select * from view_venda_detalhes where codv=0");
        this.preencherTabelaParcelas("select * from view_venda_parcelada where codpr=0");
        jTextFieldPesquisa.setEnabled(false);
        jFormattedTextFieldDataIni.setEnabled(true);
        jFormattedTextFieldDataFim.setEnabled(true);
        jFormattedTextFieldHoraIni.setEnabled(true);
        jFormattedTextFieldHoraFim.setEnabled(true);
    }//GEN-LAST:event_jRadioButtonDataHoraVendaMouseClicked

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonEfetuarPagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEfetuarPagActionPerformed
        if (flag == 1) {
            int codVenda = (int) tabela.getValueAt(tabela.getSelectedRow(), 0);
            int numParc = (int) tabelaParcelasVenda.getValueAt(tabelaParcelasVenda.getSelectedRow(), 0);
            //pra não dar erro de clique mal feito
            if (codVenda == codv) {
                if (!"PAGA".equals(String.valueOf(tabelaParcelasVenda.getValueAt(tabelaParcelasVenda.getSelectedRow(), 3)))) {
                    this.alterarSituacao(codVenda, numParc);
                    this.preencherTabelaParcelas("select * from view_venda_parcelada where codv =" + codVenda + " order by num_parcela");
                } else {
                    JOptionPane.showMessageDialog(null, "Esta parcela já está paga!");
                }
            }
        }
    }//GEN-LAST:event_jButtonEfetuarPagActionPerformed

    private void jButtonAjudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAjudaActionPerformed
        new TelaAjudaParcVenda().setVisible(true);
    }//GEN-LAST:event_jButtonAjudaActionPerformed

    private void tabelaParcelasVendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaParcelasVendaMouseClicked
        flag = 1;
    }//GEN-LAST:event_tabelaParcelasVendaMouseClicked

    private void tabelaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMousePressed
        int codVenda = (int) tabela.getValueAt(tabela.getSelectedRow(), 0);
        this.preencherTabelaParcelas("select * from view_venda_parcelada where codv =" + codVenda + " order by num_parcela");
    }//GEN-LAST:event_tabelaMousePressed

    private void jRadioButtonClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonClienteActionPerformed
        flag = 0;
        this.preencherTabela("select * from view_venda_detalhes where codv=0");
        this.preencherTabelaParcelas("select * from view_venda_parcelada where codpr=0");
        jTextFieldPesquisa.setEnabled(true);
        jFormattedTextFieldDataIni.setEnabled(false);
        jFormattedTextFieldDataFim.setEnabled(false);
        jFormattedTextFieldHoraIni.setEnabled(false);
        jFormattedTextFieldHoraFim.setEnabled(false);
    }//GEN-LAST:event_jRadioButtonClienteActionPerformed

    private void jRadioButtonCodVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCodVendaActionPerformed
        flag = 0;
        this.preencherTabela("select * from view_venda_detalhes where codv=0");
        this.preencherTabelaParcelas("select * from view_venda_parcelada where codpr=0");
        jTextFieldPesquisa.setEnabled(true);
        jFormattedTextFieldDataIni.setEnabled(false);
        jFormattedTextFieldDataFim.setEnabled(false);
        jFormattedTextFieldHoraIni.setEnabled(false);
        jFormattedTextFieldHoraFim.setEnabled(false);
    }//GEN-LAST:event_jRadioButtonCodVendaActionPerformed

    private void jRadioButtonDataHoraVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonDataHoraVendaActionPerformed
        flag = 0;
        this.preencherTabela("select * from view_venda_detalhes where codv=0");
        this.preencherTabelaParcelas("select * from view_venda_parcelada where codpr=0");
        jTextFieldPesquisa.setEnabled(false);
        jFormattedTextFieldDataIni.setEnabled(true);
        jFormattedTextFieldDataFim.setEnabled(true);
        jFormattedTextFieldHoraIni.setEnabled(true);
        jFormattedTextFieldHoraFim.setEnabled(true);
    }//GEN-LAST:event_jRadioButtonDataHoraVendaActionPerformed

    private void preencherTabela(String sql) {
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"Código", "Cliente", "Data", "Hora", "Valor R$"};
        int i = 0;
        conex.conexao();
        conex.executaSQL(sql);
        try {
            conex.rs.first();
            do {
                i++;
                SimpleDateFormat formatBra = new SimpleDateFormat("dd/MM/yyyy");
                dados.add(new Object[]{conex.rs.getInt("codv"), conex.rs.getString("nome_cliente"),
                    formatBra.format(conex.rs.getDate("data")), conex.rs.getTime("hora"),
                    conex.rs.getBigDecimal("total")});
            } while (conex.rs.next());
        } catch (SQLException ex) {
            //JOptionPane.showMessageDialog(this, "Erro ao preencher Arraylist!\n"+ex.getMessage());
        }

        ModeloTabela modelotabela = new ModeloTabela(dados, colunas);
        tabela.setModel(modelotabela);
        if (i > 4) {
            tabela.getColumnModel().getColumn(0).setPreferredWidth(67);
            tabela.getColumnModel().getColumn(1).setPreferredWidth(157);
            tabela.getColumnModel().getColumn(2).setPreferredWidth(74);
            tabela.getColumnModel().getColumn(3).setPreferredWidth(60);
            tabela.getColumnModel().getColumn(4).setPreferredWidth(76);
        } else {
            tabela.getColumnModel().getColumn(0).setPreferredWidth(70);
            tabela.getColumnModel().getColumn(1).setPreferredWidth(160);
            tabela.getColumnModel().getColumn(2).setPreferredWidth(77);
            tabela.getColumnModel().getColumn(3).setPreferredWidth(63);
            tabela.getColumnModel().getColumn(4).setPreferredWidth(80);
        }
        tabela.getColumnModel().getColumn(0).setResizable(false);
        tabela.getColumnModel().getColumn(1).setResizable(false);
        tabela.getColumnModel().getColumn(2).setResizable(false);
        tabela.getColumnModel().getColumn(3).setResizable(false);
        tabela.getColumnModel().getColumn(4).setResizable(false);
        tabela.getTableHeader().setReorderingAllowed(false);
        tabela.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tabela.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        DefaultTableCellRenderer direita = new DefaultTableCellRenderer();
        direita.setHorizontalAlignment(SwingConstants.RIGHT);
        tabela.getColumnModel().getColumn(2).setCellRenderer(direita);
        tabela.getColumnModel().getColumn(3).setCellRenderer(direita);
        tabela.getColumnModel().getColumn(4).setCellRenderer(direita);

        conex.desconecta();
    }

    private void preencherTabelaParcelas(String sql) {
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"Número", "Valor R$", "Vencimento", "Situação"};
        int i = 0;
        conex.conexao();
        conex.executaSQL(sql);
        try {
            conex.rs.first();
            codv = conex.rs.getInt("codv");
            do {
                i++;
                SimpleDateFormat formatBra = new SimpleDateFormat("dd/MM/yyyy");
                dados.add(new Object[]{conex.rs.getInt("num_parcela"), conex.rs.getBigDecimal("valor_parcela"),
                    formatBra.format(conex.rs.getDate("data_vencimento")), conex.rs.getString("situacao")});
            } while (conex.rs.next());
        } catch (SQLException ex) {
            //JOptionPane.showMessageDialog(this, "Erro ao preencher Arraylist!\n"+ex.getMessage());
        }

        ModeloTabela modelotabela = new ModeloTabela(dados, colunas);
        tabelaParcelasVenda.setModel(modelotabela);
        if (i > 4) {
            tabelaParcelasVenda.getColumnModel().getColumn(0).setPreferredWidth(108);
            tabelaParcelasVenda.getColumnModel().getColumn(1).setPreferredWidth(108);
            tabelaParcelasVenda.getColumnModel().getColumn(2).setPreferredWidth(102);
            tabelaParcelasVenda.getColumnModel().getColumn(3).setPreferredWidth(116);
        } else {
            tabelaParcelasVenda.getColumnModel().getColumn(0).setPreferredWidth(112);
            tabelaParcelasVenda.getColumnModel().getColumn(1).setPreferredWidth(112);
            tabelaParcelasVenda.getColumnModel().getColumn(2).setPreferredWidth(106);
            tabelaParcelasVenda.getColumnModel().getColumn(3).setPreferredWidth(120);
        }
        tabelaParcelasVenda.getColumnModel().getColumn(0).setResizable(false);
        tabelaParcelasVenda.getColumnModel().getColumn(1).setResizable(false);
        tabelaParcelasVenda.getColumnModel().getColumn(2).setResizable(false);
        tabelaParcelasVenda.getColumnModel().getColumn(3).setResizable(false);
        tabelaParcelasVenda.getTableHeader().setReorderingAllowed(false);
        tabelaParcelasVenda.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tabelaParcelasVenda.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        DefaultTableCellRenderer direita = new DefaultTableCellRenderer();
        direita.setHorizontalAlignment(SwingConstants.RIGHT);
        tabelaParcelasVenda.getColumnModel().getColumn(1).setCellRenderer(direita);
        tabelaParcelasVenda.getColumnModel().getColumn(2).setCellRenderer(direita);

        conex.desconecta();
    }

    public void alterarSituacao(int codVenda, int numParc) {
        conex.conexao();
        try {
            PreparedStatement pst = conex.conn.prepareStatement("update parcela_venda set situacao='PAGA' where codv=? and num_parcela=?");
            pst.setInt(1, codVenda);
            pst.setInt(2, numParc);
            pst.execute();

            JOptionPane.showMessageDialog(null, "Parcela paga com sucesso!");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao pagar o produto!\n" + ex.getMessage().replaceAll("ERROR:", ""));
        }
        conex.desconecta();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaParcelamentoVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TelaParcelamentoVenda().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonAjuda;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEfetuarPag;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JFormattedTextField jFormattedTextFieldDataFim;
    private javax.swing.JFormattedTextField jFormattedTextFieldDataIni;
    private javax.swing.JFormattedTextField jFormattedTextFieldHoraFim;
    private javax.swing.JFormattedTextField jFormattedTextFieldHoraIni;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonCliente;
    private javax.swing.JRadioButton jRadioButtonCodVenda;
    private javax.swing.JRadioButton jRadioButtonDataHoraVenda;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextFieldPesquisa;
    private javax.swing.JTable tabela;
    private javax.swing.JTable tabelaParcelasVenda;
    // End of variables declaration//GEN-END:variables
}
