/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import controle.ControleProduto;
import entidade.CProduto;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import util.ConectaBanco;
import entidade.JMoneyField;
import java.math.BigDecimal;

/**
 *
 * @author Henike
 */
public class TelaNovoProduto extends javax.swing.JFrame {

    ConectaBanco conex = ConectaBanco.getInstance();
    CProduto produto = new CProduto();
    ControleProduto control = new ControleProduto();
    int flag = 0;

    /**
     * Creates new form TelaCadastroProduto
     */
    public TelaNovoProduto() {
        initComponents();
        getRootPane().setDefaultButton(jButtonSalvar);

        try {
            MaskFormatter form = new MaskFormatter("##/##/####");
            jFormattedTextFieldData.setFormatterFactory(new DefaultFormatterFactory(form));
        } catch (ParseException ex) {
            //Logger.getLogger(TelaCadastroTelefone.class.getName()).log(Level.SEVERE, null, ex);
        }

        SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        Date hoje = new Date();
        jFormattedTextFieldData.setText(df.format(hoje));

        this.preencherComboForn();
        this.preencherComboCat();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldProduto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldQtde = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxForn = new javax.swing.JComboBox();
        jButtonSalvar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jFormattedTextFieldData = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldCodBar = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldLucro = new javax.swing.JTextField();
        jTextFieldEstMin = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jComboBoxCat = new javax.swing.JComboBox();
        jButtonAjuda = new javax.swing.JButton();
        jFormattedTextFieldPrecoVenda = new JMoneyField();
        jFormattedTextFieldPrecoComp = new JMoneyField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Novo produto");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Novo produto");

        jLabel3.setText("Produto:");

        jTextFieldProduto.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        jLabel4.setText("Quantidade:");

        jTextFieldQtde.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldQtde.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldQtdeKeyTyped(evt);
            }
        });

        jLabel5.setText("Preço de Compra R$:");

        jLabel6.setText("Preço de Venda R$:");

        jLabel7.setText("Fornecedor:");

        jComboBoxForn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jComboBoxFornMouseEntered(evt);
            }
        });

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jLabel9.setText("Data:");

        jFormattedTextFieldData.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jFormattedTextFieldData.setEnabled(false);

        jLabel10.setText("Código:");

        jLabel11.setText("Estoque mínimo:");

        jLabel12.setText("Lucro R$:");

        jTextFieldLucro.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldLucro.setEnabled(false);

        jTextFieldEstMin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldEstMinKeyTyped(evt);
            }
        });

        jLabel8.setText("Categoria:");

        jComboBoxCat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jComboBoxCatMouseEntered(evt);
            }
        });

        jButtonAjuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telas/help.gif"))); // NOI18N
        jButtonAjuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAjudaActionPerformed(evt);
            }
        });

        jFormattedTextFieldPrecoVenda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jFormattedTextFieldPrecoVendaKeyReleased(evt);
            }
        });

        jFormattedTextFieldPrecoComp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jFormattedTextFieldPrecoCompKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonSalvar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldQtde)
                            .addComponent(jComboBoxForn, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldCodBar)
                            .addComponent(jFormattedTextFieldPrecoVenda)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel7))
                                .addGap(0, 53, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(168, 168, 168)
                                    .addComponent(jButtonAjuda))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel5)
                                            .addComponent(jTextFieldEstMin, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                            .addComponent(jFormattedTextFieldPrecoComp))
                                        .addGap(22, 22, 22)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldLucro, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel12)
                                            .addComponent(jFormattedTextFieldData)))
                                    .addComponent(jButtonCancelar, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextFieldProduto, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addComponent(jLabel8)
                            .addComponent(jComboBoxCat, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jButtonAjuda))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCodBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(jLabel12)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldQtde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldEstMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldLucro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextFieldData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldPrecoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldPrecoComp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxForn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalvar)
                    .addComponent(jButtonCancelar))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(649, 414));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jComboBoxFornMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxFornMouseEntered
        this.preencherComboForn();
    }//GEN-LAST:event_jComboBoxFornMouseEntered

    private void jComboBoxCatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxCatMouseEntered
        this.preencherComboCat();
    }//GEN-LAST:event_jComboBoxCatMouseEntered

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        try {
            produto.setCod_barras(jTextFieldCodBar.getText());
            produto.setNome(jTextFieldProduto.getText());
            produto.setQuantidade(Integer.parseInt(jTextFieldQtde.getText()));
            produto.setEstoque_minimo(Integer.parseInt(jTextFieldEstMin.getText()));
            String precoComp = jFormattedTextFieldPrecoComp.getText().replace(",", ".");
            String precoVenda = jFormattedTextFieldPrecoVenda.getText().replace(",", ".");
            produto.setPreco_compra(Float.parseFloat(precoComp));
            produto.setPreco_venda(Float.parseFloat(precoVenda));
            produto.setData(jFormattedTextFieldData.getText());
            produto.setFornecedor((String) jComboBoxForn.getSelectedItem());
            produto.setCategoria((String) jComboBoxCat.getSelectedItem());

            if (control.inserir(produto)) {
                this.estadoInicial();
                flag = 0;
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Erro ao inserir o produto!\nVerifique os campos numéricos.");
        }
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonAjudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAjudaActionPerformed
        new TelaAjudaNovoProduto().setVisible(true);
    }//GEN-LAST:event_jButtonAjudaActionPerformed

    private void jTextFieldQtdeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldQtdeKeyTyped
        try {
            if (jTextFieldQtde.getText().length() > 5) {
                evt.consume();
            } else {
                Integer.parseInt(String.valueOf(evt.getKeyChar()));
            }
        } catch (NumberFormatException err) {
            //System.out.println("Informe apenas números!");
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldQtdeKeyTyped

    private void jTextFieldEstMinKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldEstMinKeyTyped
        try {
            if (jTextFieldEstMin.getText().length() > 5) {
                evt.consume();
            } else {
                Integer.parseInt(String.valueOf(evt.getKeyChar()));
            }
        } catch (NumberFormatException err) {
            //System.out.println("Informe apenas números!");
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldEstMinKeyTyped

    private void jFormattedTextFieldPrecoVendaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextFieldPrecoVendaKeyReleased
        try {
            String precoVenda = jFormattedTextFieldPrecoVenda.getText().replace(",", ".");
            BigDecimal lucro = new BigDecimal(Float.parseFloat(precoVenda) - Float.parseFloat(jFormattedTextFieldPrecoComp.getText())).setScale(2, BigDecimal.ROUND_HALF_UP);
            jTextFieldLucro.setText(String.valueOf(lucro));
        } catch (NumberFormatException ex) {
            //JOptionPane.showMessageDialog(this, "Descontos inválido!!!!!");
        }
    }//GEN-LAST:event_jFormattedTextFieldPrecoVendaKeyReleased

    private void jFormattedTextFieldPrecoCompKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextFieldPrecoCompKeyReleased
        try {
            String precoVenda = jFormattedTextFieldPrecoVenda.getText().replace(",", ".");
            BigDecimal lucro = new BigDecimal(Float.parseFloat(precoVenda) - Float.parseFloat(jFormattedTextFieldPrecoComp.getText())).setScale(2, BigDecimal.ROUND_HALF_UP);
            jTextFieldLucro.setText(String.valueOf(lucro));
        } catch (NumberFormatException ex) {
            //JOptionPane.showMessageDialog(this, "Descontos inválido!!!!!");
        }
    }//GEN-LAST:event_jFormattedTextFieldPrecoCompKeyReleased

    private void preencherComboForn() {
        conex.conexao();
        conex.executaSQL("select * from fornecedor order by nome");
        Object obj = jComboBoxForn.getSelectedItem();
        jComboBoxForn.removeAllItems();
        jComboBoxForn.addItem("");
        try {
            conex.rs.first();
            do {
                jComboBoxForn.addItem(conex.rs.getString("nome"));
            } while (conex.rs.next());
        } catch (SQLException ex) {
            //JOptionPane.showMessageDialog(this, "Erro ao preencher combobox!\n"+ex.getMessage());
        }
        jComboBoxForn.setSelectedItem(obj);
        conex.desconecta();
    }

    private void preencherComboCat() {
        conex.conexao();
        conex.executaSQL("select * from categoria order by nome");
        Object obj = jComboBoxCat.getSelectedItem();
        jComboBoxCat.removeAllItems();
        jComboBoxCat.addItem("");
        try {
            conex.rs.first();
            do {
                jComboBoxCat.addItem(conex.rs.getString("nome"));
            } while (conex.rs.next());
        } catch (SQLException ex) {
            //JOptionPane.showMessageDialog(this, "Erro ao preencher combobox!\n"+ex.getMessage());
        }
        jComboBoxCat.setSelectedItem(obj);
        conex.desconecta();
    }

    private void estadoInicial() {
        flag = 0;
        jTextFieldCodBar.setText("");
        jTextFieldProduto.setText("");
        jTextFieldQtde.setText("");
        jTextFieldEstMin.setText("");
        jTextFieldLucro.setText("");
        jFormattedTextFieldPrecoComp.setText("");
        jFormattedTextFieldPrecoVenda.setText("");
        jComboBoxForn.setSelectedItem("");
        jComboBoxCat.setSelectedItem("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaNovoProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TelaNovoProduto().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAjuda;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox jComboBoxCat;
    private javax.swing.JComboBox jComboBoxForn;
    private javax.swing.JFormattedTextField jFormattedTextFieldData;
    private javax.swing.JFormattedTextField jFormattedTextFieldPrecoComp;
    private javax.swing.JFormattedTextField jFormattedTextFieldPrecoVenda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldCodBar;
    private javax.swing.JTextField jTextFieldEstMin;
    private javax.swing.JTextField jTextFieldLucro;
    private javax.swing.JTextField jTextFieldProduto;
    private javax.swing.JTextField jTextFieldQtde;
    // End of variables declaration//GEN-END:variables
}
