/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import controle.ControleUsuario;
import entidade.CUsuario;
import entidade.CPrivilegios;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import util.ConectaBanco;

/**
 *
 * @author Henike
 */
public class TelaAlterarUsuario extends javax.swing.JFrame {

    CUsuario usuario = new CUsuario();
    CPrivilegios privilegios = new CPrivilegios();
    ControleUsuario control = new ControleUsuario();
    ConectaBanco conex = ConectaBanco.getInstance();
    int flag = 0;

    /**
     * Creates new form TelaCadastroLogin
     *
     * @param nome
     */
    public TelaAlterarUsuario(String nome) {
        initComponents();
        getRootPane().setDefaultButton(jButtonSalvar);

        conex.conexao();
        conex.executaSQL("select * from view_usuario_detalhes where nome='" + nome + "'");
        try {
            conex.rs.first();
            usuario.setCodu(conex.rs.getInt("codu"));
            jTextFieldLogin.setText(conex.rs.getString("login"));
            jTextFieldNome.setText(conex.rs.getString("nome"));
            privilegios.setCodpv(conex.rs.getInt("codpv"));
            jCheckBoxCadLogins.setSelected(conex.rs.getBoolean("logins"));
            jCheckBoxCadCat.setSelected(conex.rs.getBoolean("categorias"));
            jCheckBoxCadClientes.setSelected(conex.rs.getBoolean("clientes"));
            jCheckBoxCadForn.setSelected(conex.rs.getBoolean("fornecedores"));
            jCheckBoxCadProd.setSelected(conex.rs.getBoolean("produtos"));
            jCheckBoxPesqVendas.setSelected(conex.rs.getBoolean("pesq_vendas"));
            jCheckBoxVendas.setSelected(conex.rs.getBoolean("efetuar_vendas"));
            jCheckBoxRelatorios.setSelected(conex.rs.getBoolean("relatorios"));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Erro ao selecionar os dados!\n" + ex.getMessage().replaceAll("ERROR:", ""));
        }
        conex.desconecta();
    }

    private TelaAlterarUsuario() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jPasswordFieldSenha = new javax.swing.JPasswordField();
        jPasswordFieldConfSenha = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldLogin = new javax.swing.JTextField();
        jButtonSalvar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jCheckBoxCadCat = new javax.swing.JCheckBox();
        jCheckBoxCadLogins = new javax.swing.JCheckBox();
        jCheckBoxCadClientes = new javax.swing.JCheckBox();
        jCheckBoxCadForn = new javax.swing.JCheckBox();
        jCheckBoxCadProd = new javax.swing.JCheckBox();
        jCheckBoxPesqVendas = new javax.swing.JCheckBox();
        jCheckBoxVendas = new javax.swing.JCheckBox();
        jCheckBoxRelatorios = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jButtonAjuda = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alterar usuário");
        setResizable(false);

        jPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Alterar usuário");

        jLabel3.setText("Nome:");

        jLabel4.setText("Senha:");

        jLabel5.setText("Confirmação de Senha:");

        jTextFieldNome.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        jPasswordFieldSenha.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        jPasswordFieldConfSenha.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        jLabel6.setText("Login:");

        jTextFieldLogin.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jCheckBoxCadCat.setText("Cadastrar Categorias");

        jCheckBoxCadLogins.setText("Cadastrar Usuários");

        jCheckBoxCadClientes.setText("Cadastrar Clientes");

        jCheckBoxCadForn.setText("Cadastrar Fornecedores");

        jCheckBoxCadProd.setText("Cadastrar Produtos");

        jCheckBoxPesqVendas.setText("Pesquisar Vendas");

        jCheckBoxVendas.setText("Realizar Vendas");

        jCheckBoxRelatorios.setText("Gerar Relatórios");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Privilégios de Acesso:");

        jButtonAjuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telas/help.gif"))); // NOI18N
        jButtonAjuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAjudaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxCadCat)
                            .addComponent(jCheckBoxCadLogins)
                            .addComponent(jCheckBoxRelatorios))
                        .addGap(53, 53, 53)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxVendas)
                            .addComponent(jCheckBoxCadClientes)
                            .addComponent(jCheckBoxCadForn))
                        .addGap(53, 53, 53)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxPesqVendas)
                            .addComponent(jCheckBoxCadProd)))
                    .addComponent(jLabel2)
                    .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanelLayout.createSequentialGroup()
                            .addComponent(jButtonSalvar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jButtonExcluir)
                            .addGap(324, 324, 324)
                            .addComponent(jButtonCancelar))
                        .addGroup(jPanelLayout.createSequentialGroup()
                            .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanelLayout.createSequentialGroup()
                                    .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jPasswordFieldSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanelLayout.createSequentialGroup()
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel5))
                                        .addGroup(jPanelLayout.createSequentialGroup()
                                            .addGap(18, 18, 18)
                                            .addComponent(jPasswordFieldConfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGap(18, 18, 18)
                            .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldLogin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanelLayout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(159, 159, 159)
                            .addComponent(jButtonAjuda))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jButtonAjuda))
                .addGap(30, 30, 30)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(3, 3, 3)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordFieldSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordFieldConfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxCadLogins)
                    .addComponent(jCheckBoxCadClientes)
                    .addComponent(jCheckBoxCadProd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxCadCat)
                    .addComponent(jCheckBoxCadForn)
                    .addComponent(jCheckBoxPesqVendas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxRelatorios)
                    .addComponent(jCheckBoxVendas))
                .addGap(26, 26, 26)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalvar)
                    .addComponent(jButtonExcluir)
                    .addComponent(jButtonCancelar))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(639, 429));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        if (jPasswordFieldSenha.getText().equals(jPasswordFieldConfSenha.getText())) {
            usuario.setLogin(jTextFieldLogin.getText());
            usuario.setNome(jTextFieldNome.getText());
            //login.setPermissao((String)jComboBoxPerm.getSelectedItem());
            usuario.setSenha(jPasswordFieldSenha.getText());

            privilegios.setLogins(jCheckBoxCadLogins.isSelected());
            privilegios.setCategorias(jCheckBoxCadCat.isSelected());
            privilegios.setClientes(jCheckBoxCadClientes.isSelected());
            privilegios.setFornecedores(jCheckBoxCadForn.isSelected());
            privilegios.setProdutos(jCheckBoxCadProd.isSelected());
            privilegios.setPesq_vendas(jCheckBoxPesqVendas.isSelected());
            privilegios.setEfetuar_vendas(jCheckBoxVendas.isSelected());
            privilegios.setRelatorios(jCheckBoxRelatorios.isSelected());

            if (control.alterar(usuario, privilegios)) {
                this.dispose();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao alterar o usuário!\nAs senhas não correspondem.");
        }
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        if (JOptionPane.showConfirmDialog(rootPane, "Deseja realmente excluir?", "Confirmar Exclusão", JOptionPane.YES_NO_OPTION) == 0) {
            //usuario.setCodu(Integer.parseInt(jTextFieldCod.getText()));
            usuario.setLogin(jTextFieldLogin.getText());
            usuario.setNome(jTextFieldNome.getText());
            usuario.setCodpv(privilegios.getCodpv());
            //login.setPermissao((String)jComboBoxPerm.getSelectedItem());
            control.excluir(usuario);
            this.dispose();
        }
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonAjudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAjudaActionPerformed
        new TelaAjudaAltUsuario().setVisible(true);
    }//GEN-LAST:event_jButtonAjudaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAlterarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TelaAlterarUsuario().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAjuda;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JCheckBox jCheckBoxCadCat;
    private javax.swing.JCheckBox jCheckBoxCadClientes;
    private javax.swing.JCheckBox jCheckBoxCadForn;
    private javax.swing.JCheckBox jCheckBoxCadLogins;
    private javax.swing.JCheckBox jCheckBoxCadProd;
    private javax.swing.JCheckBox jCheckBoxPesqVendas;
    private javax.swing.JCheckBox jCheckBoxRelatorios;
    private javax.swing.JCheckBox jCheckBoxVendas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel;
    private javax.swing.JPasswordField jPasswordFieldConfSenha;
    private javax.swing.JPasswordField jPasswordFieldSenha;
    private javax.swing.JTextField jTextFieldLogin;
    private javax.swing.JTextField jTextFieldNome;
    // End of variables declaration//GEN-END:variables

}
