/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import java.sql.Date;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import util.ConectaBanco;

/**
 *
 * @author Henike
 */
public class TelaRelatorios extends javax.swing.JFrame {

    ConectaBanco conex = ConectaBanco.getInstance();
    SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
    java.util.Date hoje = new java.util.Date();

    /**
     * Creates new form TelaRelatorios
     */
    public TelaRelatorios() {
        initComponents();
        getRootPane().setDefaultButton(jButtonGerarRel);

        try {
            MaskFormatter formdiaini = new MaskFormatter("##/##/####");
            jFormattedTextFieldDataIni.setFormatterFactory(new DefaultFormatterFactory(formdiaini));
            jFormattedTextFieldDataFinal.setFormatterFactory(new DefaultFormatterFactory(formdiaini));

            jFormattedTextFieldDataIni.setText(df.format(hoje));
            jFormattedTextFieldDataFinal.setText(df.format(hoje));
        } catch (ParseException ex) {
            //Logger.getLogger(TelaRelatorios.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jRadioButtonCli = new javax.swing.JRadioButton();
        jRadioButtonForn = new javax.swing.JRadioButton();
        jRadioButtonProd = new javax.swing.JRadioButton();
        jRadioButtonVenda = new javax.swing.JRadioButton();
        jFormattedTextFieldDataIni = new javax.swing.JFormattedTextField();
        jFormattedTextFieldDataFinal = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonGerarRel = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxTipo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButtonAlterar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gerar Relatório");
        setResizable(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        buttonGroup1.add(jRadioButtonCli);
        jRadioButtonCli.setText("Cliente");
        jRadioButtonCli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonCliMouseClicked(evt);
            }
        });
        jRadioButtonCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCliActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonForn);
        jRadioButtonForn.setText("Fornecedor");
        jRadioButtonForn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonFornMouseClicked(evt);
            }
        });
        jRadioButtonForn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonFornActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonProd);
        jRadioButtonProd.setText("Produto");
        jRadioButtonProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonProdMouseClicked(evt);
            }
        });
        jRadioButtonProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonProdActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonVenda);
        jRadioButtonVenda.setText("Venda");
        jRadioButtonVenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonVendaMouseClicked(evt);
            }
        });
        jRadioButtonVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonVendaActionPerformed(evt);
            }
        });

        jFormattedTextFieldDataIni.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        jFormattedTextFieldDataFinal.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        jLabel1.setText("Data inicial:");

        jLabel2.setText("Data final:");

        jButtonGerarRel.setText("Gerar relatório");
        jButtonGerarRel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGerarRelActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jLabel3.setText("Relatório de:");

        jComboBoxTipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jComboBoxTipoMouseEntered(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Gerar Relatório");

        jLabel5.setText("Classificar por:");

        jButtonAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telas/help.gif"))); // NOI18N
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonAlterar)
                        .addGap(42, 42, 42))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jFormattedTextFieldDataIni, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jFormattedTextFieldDataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jComboBoxTipo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButtonCli)
                                    .addComponent(jRadioButtonProd))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButtonForn)
                                    .addComponent(jRadioButtonVenda))))
                        .addGap(37, 37, 37))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonGerarRel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonCancelar)
                        .addGap(45, 45, 45))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jButtonAlterar))
                .addGap(35, 35, 35)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonCli)
                    .addComponent(jRadioButtonForn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonProd)
                    .addComponent(jRadioButtonVenda))
                .addGap(27, 27, 27)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextFieldDataIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldDataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGerarRel)
                    .addComponent(jButtonCancelar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(365, 426));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jRadioButtonCliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonCliMouseClicked
        this.preencherComboBox(jRadioButtonCli.getText());
    }//GEN-LAST:event_jRadioButtonCliMouseClicked

    private void jRadioButtonFornMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonFornMouseClicked
        this.preencherComboBox(jRadioButtonForn.getText());
    }//GEN-LAST:event_jRadioButtonFornMouseClicked

    private void jRadioButtonProdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonProdMouseClicked
        this.preencherComboBox(jRadioButtonProd.getText());
    }//GEN-LAST:event_jRadioButtonProdMouseClicked

    private void jRadioButtonVendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonVendaMouseClicked
        this.preencherComboBox(jRadioButtonVenda.getText());
    }//GEN-LAST:event_jRadioButtonVendaMouseClicked

    private void jButtonGerarRelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGerarRelActionPerformed
        if (jComboBoxTipo.getSelectedItem() == null) {
            return;
        }
        if (jComboBoxTipo.getSelectedItem().equals("Produtos Cadastrados")) {
            conex.conexao();
            try {
                SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
                format.setLenient(false);
                Date dataIni = new Date(format.parse(jFormattedTextFieldDataIni.getText()).getTime());
                Date dataFim = new Date(format.parse(jFormattedTextFieldDataFinal.getText()).getTime());

                if (!dataIni.after(dataFim)) {
                    conex.executaSQL("select * from \n"
                            + "(select vpd.nome,\n"
                            + "   max(vpd.data) AS data\n"
                            + "   from view_produtos_detalhes vpd\n"
                            + "   where vpd.data <= '" + dataFim + "' group by vpd.nome) vpd\n"
                            + "inner join view_produtos_detalhes vpde on vpde.nome = vpd.nome and vpde.data = vpd.data \n"
                            + "order by vpd.nome");

                    JRResultSetDataSource relatResul = new JRResultSetDataSource(conex.rs);// Passa um resultSet preenchido para o relatório!
                    Map parametros = new HashMap();
                    parametros.put("Parameter1", jFormattedTextFieldDataIni.getText());
                    parametros.put("Parameter2", jFormattedTextFieldDataFinal.getText());
                    JasperPrint jpPrint = JasperFillManager.fillReport("iReport/relatorioBrancoProdutoCad.jasper", parametros, relatResul);// Indica o caminho para pegar o modelo do relatório
                    //JasperPrint jpPrint = JasperFillManager.fillReport("iReport/relatorioBrancoProdutoCad.jasper", new HashMap(), relatResul);// Indica o caminho para pegar o modelo do relatório
                    JasperViewer jv = new JasperViewer(jpPrint, false);// Cria instância para impressão (setar false para não fechar toda a aplicação!!!)
                    jv.setVisible(true);// Relatório para visualização
                    jv.toFront(); // Seta o formulário na frente da aplicação
                }
            } catch (JRException ex) {
                JOptionPane.showMessageDialog(this, "Erro ao chamar o relatório!\nERRO:" + ex);
            } catch (ParseException ex) {
                //Logger.getLogger(TelaRelatorios.class.getName()).log(Level.SEVERE, null, ex);
            }
            conex.desconecta();
        } else if (jComboBoxTipo.getSelectedItem().equals("Estoque insuficiente")) {
            conex.conexao();
            try {
                conex.executaSQL("select * from view_produtos_recentes_detalhes where quantidade < estoque_minimo order by nome");
                JRResultSetDataSource relatResul = new JRResultSetDataSource(conex.rs);// Passa um resultSet preenchido para o relatório!
                JasperPrint jpPrint = JasperFillManager.fillReport("iReport/relatorioBrancoEstInsuficiente.jasper", new HashMap(), relatResul);// Indica o caminho para pegar o modelo do relatório
                JasperViewer jv = new JasperViewer(jpPrint, false);// Cria instância para impressão (setar false para não fechar toda a aplicação!!!)
                jv.setVisible(true);// Relatório para visualização
                jv.toFront(); // Seta o formulário na frente da aplicação
            } catch (JRException ex) {
                JOptionPane.showMessageDialog(this, "Erro ao chamar o relatório!\nERRO:" + ex);
            }
            conex.desconecta();
        } else if (jComboBoxTipo.getSelectedItem().equals("Produtos não vendidos")) {
            conex.conexao();
            try {
                conex.executaSQL("select * from view_produtos_recentes_detalhes vpr \n"
                        + "where not exists (select 1 from view_produtos_venda vg \n"
                        + "where vg.nome = vpr.nome) order by nome");
                JRResultSetDataSource relatResul = new JRResultSetDataSource(conex.rs);// Passa um resultSet preenchido para o relatório!
                JasperPrint jpPrint = JasperFillManager.fillReport("iReport/relatorioBrancoProdutoSemVenda.jasper", new HashMap(), relatResul);// Indica o caminho para pegar o modelo do relatório
                JasperViewer jv = new JasperViewer(jpPrint, false);// Cria instância para impressão (setar false para não fechar toda a aplicação!!!)
                jv.setVisible(true);// Relatório para visualização
                jv.toFront(); // Seta o formulário na frente da aplicação
            } catch (JRException ex) {
                JOptionPane.showMessageDialog(this, "Erro ao chamar o relatório!\nERRO:" + ex);
            }
            conex.desconecta();
        } else if (jComboBoxTipo.getSelectedItem().equals("Produtos mais vendidos")) {
            conex.conexao();
            try {
                conex.executaSQL("select * from view_produtos_mais_vendidos");
                JRResultSetDataSource relatResul = new JRResultSetDataSource(conex.rs);// Passa um resultSet preenchido para o relatório!
                JasperPrint jpPrint = JasperFillManager.fillReport("iReport/relatorioBrancoProdutoMaisVend.jasper", new HashMap(), relatResul);// Indica o caminho para pegar o modelo do relatório
                JasperViewer jv = new JasperViewer(jpPrint, false);// Cria instância para impressão (setar false para não fechar toda a aplicação!!!)
                jv.setVisible(true);// Relatório para visualização
                jv.toFront(); // Seta o formulário na frente da aplicação
            } catch (JRException ex) {
                JOptionPane.showMessageDialog(this, "Erro ao chamar o relatório!\nERRO:" + ex);
            }
            conex.desconecta();
        } else if (jComboBoxTipo.getSelectedItem().equals("Fornecedores cadastrados")) {
            conex.conexao();
            try {
                conex.executaSQL("select * from view_fornecedor_detalhes order by nome");
                JRResultSetDataSource relatResul = new JRResultSetDataSource(conex.rs);// Passa um resultSet preenchido para o relatório!
                JasperPrint jpPrint = JasperFillManager.fillReport("iReport/relatorioBrancoFornecedor.jasper", new HashMap(), relatResul);// Indica o caminho para pegar o modelo do relatório
                JasperViewer jv = new JasperViewer(jpPrint, false);// Cria instância para impressão (setar false para não fechar toda a aplicação!!!)
                jv.setVisible(true);// Relatório para visualização
                jv.toFront(); // Seta o formulário na frente da aplicação
            } catch (JRException ex) {
                JOptionPane.showMessageDialog(this, "Erro ao chamar o relatório!\nERRO:" + ex);
            }
            conex.desconecta();
        } else if (jComboBoxTipo.getSelectedItem().equals("Clientes cadastrados")) {
            conex.conexao();
            try {
                conex.executaSQL("select * from view_cliente_detalhes order by nome");
                JRResultSetDataSource relatResul = new JRResultSetDataSource(conex.rs);// Passa um resultSet preenchido para o relatório!
                JasperPrint jpPrint = JasperFillManager.fillReport("iReport/relatorioBrancoCliente.jasper", new HashMap(), relatResul);// Indica o caminho para pegar o modelo do relatório
                JasperViewer jv = new JasperViewer(jpPrint, false);// Cria instância para impressão (setar false para não fechar toda a aplicação!!!)
                jv.setVisible(true);// Relatório para visualização
                jv.toFront(); // Seta o formulário na frente da aplicação
            } catch (JRException ex) {
                JOptionPane.showMessageDialog(this, "Erro ao chamar o relatório!\nERRO:" + ex);
            }
            conex.desconecta();
        } else if (jComboBoxTipo.getSelectedItem().equals("Vendas por período")) {
            conex.conexao();
            try {
                SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
                format.setLenient(false);
                Date dataIni = new Date(format.parse(jFormattedTextFieldDataIni.getText()).getTime());
                Date dataFim = new Date(format.parse(jFormattedTextFieldDataFinal.getText()).getTime());

                conex.executaSQL("select * from view_venda_detalhes where data between '" + dataIni + "' and '" + dataFim + "' order by data, hora");
                JRResultSetDataSource relatResul = new JRResultSetDataSource(conex.rs);// Passa um resultSet preenchido para o relatório!
                Map parametros = new HashMap();
                parametros.put("Parameter1", jFormattedTextFieldDataIni.getText());
                parametros.put("Parameter2", jFormattedTextFieldDataFinal.getText());
                JasperPrint jpPrint = JasperFillManager.fillReport("iReport/relatorioBrancoVendaCliente.jasper", parametros, relatResul);// Indica o caminho para pegar o modelo do relatório
                //JasperPrint jpPrint = JasperFillManager.fillReport("iReport/relatorioBrancoVendaCliente.jasper", new HashMap(), relatResul);// Indica o caminho para pegar o modelo do relatório
                JasperViewer jv = new JasperViewer(jpPrint, false);// Cria instância para impressão (setar false para não fechar toda a aplicação!!!)
                jv.setVisible(true);// Relatório para visualização
                jv.toFront(); // Seta o formulário na frente da aplicação
            } catch (JRException ex) {
                JOptionPane.showMessageDialog(this, "Erro ao chamar o relatório!\nERRO:" + ex);
            } catch (ParseException ex) {
                //Logger.getLogger(TelaRelatorios.class.getName()).log(Level.SEVERE, null, ex);
            }
            conex.desconecta();
        }
    }//GEN-LAST:event_jButtonGerarRelActionPerformed

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
        new TelaAjudaRelatorios().setVisible(true);
    }//GEN-LAST:event_jButtonAlterarActionPerformed

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        if (jComboBoxTipo.getSelectedItem() != null) {
            if (jComboBoxTipo.getSelectedItem().equals("Estoque insuficiente")
                    || jComboBoxTipo.getSelectedItem().equals("Produtos não vendidos")
                    || jComboBoxTipo.getSelectedItem().equals("Produtos mais vendidos")
                    || jComboBoxTipo.getSelectedItem().equals("Fornecedores cadastrados")
                    || jComboBoxTipo.getSelectedItem().equals("Clientes cadastrados")) {
                jFormattedTextFieldDataIni.setEnabled(false);
                jFormattedTextFieldDataFinal.setEnabled(false);
                jFormattedTextFieldDataIni.setText(df.format(hoje));
                jFormattedTextFieldDataFinal.setText(df.format(hoje));
            } else {
                jFormattedTextFieldDataIni.setEnabled(true);
                jFormattedTextFieldDataFinal.setEnabled(true);
            }
        }
    }//GEN-LAST:event_formMouseEntered

    private void jComboBoxTipoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxTipoMouseEntered
        if (jRadioButtonCli.isSelected()) {
            Object obj = jComboBoxTipo.getSelectedItem();
            this.preencherComboBox("Cliente");
            jComboBoxTipo.setSelectedItem(obj);
        } else if (jRadioButtonForn.isSelected()) {
            Object obj = jComboBoxTipo.getSelectedItem();
            this.preencherComboBox("Fornecedor");
            jComboBoxTipo.setSelectedItem(obj);
        } else if (jRadioButtonProd.isSelected()) {
            Object obj = jComboBoxTipo.getSelectedItem();
            this.preencherComboBox("Produto");
            jComboBoxTipo.setSelectedItem(obj);
        } else if (jRadioButtonVenda.isSelected()) {
            Object obj = jComboBoxTipo.getSelectedItem();
            this.preencherComboBox("Venda");
            jComboBoxTipo.setSelectedItem(obj);
        }
    }//GEN-LAST:event_jComboBoxTipoMouseEntered

    private void jRadioButtonCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCliActionPerformed
        this.preencherComboBox(jRadioButtonCli.getText());
    }//GEN-LAST:event_jRadioButtonCliActionPerformed

    private void jRadioButtonFornActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonFornActionPerformed
        this.preencherComboBox(jRadioButtonForn.getText());
    }//GEN-LAST:event_jRadioButtonFornActionPerformed

    private void jRadioButtonProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonProdActionPerformed
        this.preencherComboBox(jRadioButtonProd.getText());
    }//GEN-LAST:event_jRadioButtonProdActionPerformed

    private void jRadioButtonVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonVendaActionPerformed
        this.preencherComboBox(jRadioButtonVenda.getText());
    }//GEN-LAST:event_jRadioButtonVendaActionPerformed

    private void preencherComboBox(String opc) {
        switch (opc) {
            case "Cliente":
                jComboBoxTipo.removeAllItems();
                jComboBoxTipo.addItem("");
                jComboBoxTipo.addItem("Clientes cadastrados");
                jComboBoxTipo.setSelectedItem("Clientes cadastrados");
                break;
            case "Fornecedor":
                jComboBoxTipo.removeAllItems();
                jComboBoxTipo.addItem("");
                jComboBoxTipo.addItem("Fornecedores cadastrados");
                jComboBoxTipo.setSelectedItem("Fornecedores cadastrados");
                break;
            case "Produto":
                jComboBoxTipo.removeAllItems();
                jComboBoxTipo.addItem("");
                jComboBoxTipo.addItem("Produtos Cadastrados");
                jComboBoxTipo.addItem("Estoque insuficiente");
                jComboBoxTipo.addItem("Produtos não vendidos");
                jComboBoxTipo.addItem("Produtos mais vendidos");
                jComboBoxTipo.setSelectedItem("Produtos Cadastrados");
                break;
            case "Venda":
                jComboBoxTipo.removeAllItems();
                jComboBoxTipo.addItem("");
                jComboBoxTipo.addItem("Vendas por período");
                jComboBoxTipo.setSelectedItem("Vendas por período");
                break;
            default:
                break;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TelaRelatorios().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonGerarRel;
    private javax.swing.JComboBox<String> jComboBoxTipo;
    private javax.swing.JFormattedTextField jFormattedTextFieldDataFinal;
    private javax.swing.JFormattedTextField jFormattedTextFieldDataIni;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonCli;
    private javax.swing.JRadioButton jRadioButtonForn;
    private javax.swing.JRadioButton jRadioButtonProd;
    private javax.swing.JRadioButton jRadioButtonVenda;
    // End of variables declaration//GEN-END:variables
}
