/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import controle.ControleUsuario;
import entidade.CUsuario;
import entidade.CPrivilegios;
import entidade.ModeloTabela;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import util.ConectaBanco;

/**
 *
 * @author Henike
 */
public class Usuario extends javax.swing.JFrame {

    CUsuario usuario = new CUsuario();
    CPrivilegios privilegios = new CPrivilegios();
    ControleUsuario control = new ControleUsuario();
    ConectaBanco conex = ConectaBanco.getInstance();
    int flag = 0;

    /**
     * Creates new form TelaCadastroLogin
     */
    public Usuario() {
        initComponents();
        this.preencherTabela("select * from view_usuario_detalhes order by nome");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jPasswordFieldSenha = new javax.swing.JPasswordField();
        jPasswordFieldConfSenha = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldLogin = new javax.swing.JTextField();
        jButtonNovo = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jCheckBoxCadCat = new javax.swing.JCheckBox();
        jCheckBoxCadLogins = new javax.swing.JCheckBox();
        jCheckBoxCadClientes = new javax.swing.JCheckBox();
        jCheckBoxCadForn = new javax.swing.JCheckBox();
        jCheckBoxCadProd = new javax.swing.JCheckBox();
        jCheckBoxPesqVendas = new javax.swing.JCheckBox();
        jCheckBoxVendas = new javax.swing.JCheckBox();
        jCheckBoxRelatorios = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jTextFieldPesqUsu = new javax.swing.JTextField();
        jButtonPesquisar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar Usuário");
        setResizable(false);

        jPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Cadastrar usuário");

        jLabel3.setText("Nome:");

        jLabel4.setText("Senha:");

        jLabel5.setText("Confirmação de Senha:");

        jTextFieldNome.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldNome.setEnabled(false);

        jPasswordFieldSenha.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jPasswordFieldSenha.setEnabled(false);

        jPasswordFieldConfSenha.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jPasswordFieldConfSenha.setEnabled(false);

        jLabel6.setText("Login:");

        jTextFieldLogin.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldLogin.setEnabled(false);

        jButtonNovo.setText("Novo");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setEnabled(false);
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.setEnabled(false);
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setEnabled(false);
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        jCheckBoxCadCat.setText("Cadastrar Categorias");
        jCheckBoxCadCat.setEnabled(false);

        jCheckBoxCadLogins.setText("Cadastrar Usuários");
        jCheckBoxCadLogins.setEnabled(false);

        jCheckBoxCadClientes.setText("Cadastrar Clientes");
        jCheckBoxCadClientes.setEnabled(false);

        jCheckBoxCadForn.setText("Cadastrar Fornecedores");
        jCheckBoxCadForn.setEnabled(false);

        jCheckBoxCadProd.setText("Cadastrar Produtos");
        jCheckBoxCadProd.setEnabled(false);

        jCheckBoxPesqVendas.setText("Pesquisar Vendas");
        jCheckBoxPesqVendas.setEnabled(false);

        jCheckBoxVendas.setText("Realizar Vendas");
        jCheckBoxVendas.setEnabled(false);

        jCheckBoxRelatorios.setText("Gerar Relatórios");
        jCheckBoxRelatorios.setEnabled(false);

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela);

        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Privilégios de Acesso:");

        jLabel7.setText("Pesquisar usuário:");

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBoxCadCat)
                                    .addComponent(jCheckBoxCadLogins)
                                    .addComponent(jCheckBoxRelatorios))
                                .addGap(53, 53, 53)
                                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBoxVendas)
                                    .addComponent(jCheckBoxCadClientes)
                                    .addComponent(jCheckBoxCadForn))
                                .addGap(53, 53, 53)
                                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBoxPesqVendas)
                                    .addComponent(jCheckBoxCadProd)))
                            .addComponent(jLabel2)
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jTextFieldNome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanelLayout.createSequentialGroup()
                                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jPasswordFieldSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanelLayout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel5))
                                            .addGroup(jPanelLayout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(jPasswordFieldConfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelLayout.createSequentialGroup()
                                        .addComponent(jTextFieldPesqUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonPesquisar))
                                    .addComponent(jTextFieldLogin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addComponent(jButtonNovo)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonSalvar)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonExcluir)
                                .addGap(12, 12, 12)
                                .addComponent(jButtonCancelar)
                                .addGap(181, 181, 181)
                                .addComponent(jButtonSair)))))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(218, 218, 218))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addGap(3, 3, 3)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonPesquisar)
                        .addComponent(jTextFieldPesqUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jPasswordFieldSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPasswordFieldConfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxCadLogins)
                    .addComponent(jCheckBoxCadClientes)
                    .addComponent(jCheckBoxCadProd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxCadCat)
                    .addComponent(jCheckBoxCadForn)
                    .addComponent(jCheckBoxPesqVendas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxRelatorios)
                    .addComponent(jCheckBoxVendas))
                .addGap(25, 25, 25)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNovo)
                    .addComponent(jButtonSalvar)
                    .addComponent(jButtonExcluir)
                    .addComponent(jButtonCancelar)
                    .addComponent(jButtonSair))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(639, 545));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        flag = 1;
        jTextFieldLogin.setText("");
        jTextFieldNome.setText("");
        jPasswordFieldSenha.setText("");
        jPasswordFieldConfSenha.setText("");
        jButtonSalvar.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        jButtonSair.setEnabled(true);
        jTextFieldLogin.setEnabled(true);
        jTextFieldNome.setEnabled(true);
        jPasswordFieldSenha.setEnabled(true);
        jPasswordFieldConfSenha.setEnabled(true);
        jButtonNovo.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        jCheckBoxCadLogins.setSelected(false);
        jCheckBoxCadCat.setSelected(false);
        jCheckBoxCadClientes.setSelected(false);
        jCheckBoxCadForn.setSelected(false);
        jCheckBoxCadProd.setSelected(false);
        jCheckBoxPesqVendas.setSelected(false);
        jCheckBoxVendas.setSelected(false);
        jCheckBoxRelatorios.setSelected(false);
        jCheckBoxCadLogins.setEnabled(!false);
        jCheckBoxCadCat.setEnabled(!false);
        jCheckBoxCadClientes.setEnabled(!false);
        jCheckBoxCadForn.setEnabled(!false);
        jCheckBoxCadProd.setEnabled(!false);
        jCheckBoxPesqVendas.setEnabled(!false);
        jCheckBoxVendas.setEnabled(!false);
        jCheckBoxRelatorios.setEnabled(!false);
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        this.estadoInicial();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        if (flag == 0) {
            if (JOptionPane.showConfirmDialog(rootPane, "Deseja realmente alterar?", "Confirmar Alteração", JOptionPane.YES_NO_OPTION) == 0) {
                if (jPasswordFieldSenha.getText().equals(jPasswordFieldConfSenha.getText())) {
                    usuario.setLogin(jTextFieldLogin.getText());
                    usuario.setNome(jTextFieldNome.getText());
                    usuario.setSenha(jPasswordFieldSenha.getText());

                    privilegios.setLogins(jCheckBoxCadLogins.isSelected());
                    privilegios.setCategorias(jCheckBoxCadCat.isSelected());
                    privilegios.setClientes(jCheckBoxCadClientes.isSelected());
                    privilegios.setFornecedores(jCheckBoxCadForn.isSelected());
                    privilegios.setProdutos(jCheckBoxCadProd.isSelected());
                    privilegios.setPesq_vendas(jCheckBoxPesqVendas.isSelected());
                    privilegios.setEfetuar_vendas(jCheckBoxVendas.isSelected());
                    privilegios.setRelatorios(jCheckBoxRelatorios.isSelected());

                    if (control.alterar(usuario, privilegios)) {
                        this.estadoInicial();
                        this.preencherTabela("select * from view_usuario_detalhes order by nome");
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Erro ao alterar o usuário!\nERROR: As senhas não correspondem!");
                }
            }
        } else if (jPasswordFieldSenha.getText().equals(jPasswordFieldConfSenha.getText())) {
            usuario.setLogin(jTextFieldLogin.getText());
            usuario.setNome(jTextFieldNome.getText());
            usuario.setCodpv(privilegios.getCodpv());
            usuario.setSenha(jPasswordFieldSenha.getText());

            privilegios.setLogins(jCheckBoxCadLogins.isSelected());
            privilegios.setCategorias(jCheckBoxCadCat.isSelected());
            privilegios.setClientes(jCheckBoxCadClientes.isSelected());
            privilegios.setFornecedores(jCheckBoxCadForn.isSelected());
            privilegios.setProdutos(jCheckBoxCadProd.isSelected());
            privilegios.setPesq_vendas(jCheckBoxPesqVendas.isSelected());
            privilegios.setEfetuar_vendas(jCheckBoxVendas.isSelected());
            privilegios.setRelatorios(jCheckBoxRelatorios.isSelected());

            if (control.salvar(usuario, privilegios)) {
                this.estadoInicial();
                this.preencherTabela("select * from view_usuario_detalhes order by nome");
                flag = 0;
            }
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao inserir o usuário!\nERROR: As senhas não correspondem!");
        }
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        if (JOptionPane.showConfirmDialog(rootPane, "Deseja realmente excluir?", "Confirmar Exclusão", JOptionPane.YES_NO_OPTION) == 0) {
            usuario.setLogin(jTextFieldLogin.getText());
            usuario.setNome(jTextFieldNome.getText());
            usuario.setCodpv(privilegios.getCodpv());
            control.excluir(usuario);
            this.preencherTabela("select * from view_usuario_detalhes order by nome");
            this.estadoInicial();
        }
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        this.preencherTabela("select * from view_usuario_detalhes where nome ~* '" + jTextFieldPesqUsu.getText() + "' order by nome");
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        // não pode ser ativada quando o botão novo for acionado!!!!! 
        if (flag == 0) {
            String nome = "" + tabela.getValueAt(tabela.getSelectedRow(), 0);
            conex.conexao();
            conex.executaSQL("select * from view_usuario_detalhes where nome='" + nome + "'");
            try {
                conex.rs.first();
                usuario.setCodu(conex.rs.getInt("codu"));
                jTextFieldLogin.setText(conex.rs.getString("login"));
                jTextFieldNome.setText(conex.rs.getString("nome"));
                privilegios.setCodpv(conex.rs.getInt("codpv"));
                jCheckBoxCadLogins.setSelected(conex.rs.getBoolean("logins"));
                jCheckBoxCadCat.setSelected(conex.rs.getBoolean("categorias"));
                jCheckBoxCadClientes.setSelected(conex.rs.getBoolean("clientes"));
                jCheckBoxCadForn.setSelected(conex.rs.getBoolean("fornecedores"));
                jCheckBoxCadProd.setSelected(conex.rs.getBoolean("produtos"));
                jCheckBoxPesqVendas.setSelected(conex.rs.getBoolean("pesq_vendas"));
                jCheckBoxVendas.setSelected(conex.rs.getBoolean("efetuar_vendas"));
                jCheckBoxRelatorios.setSelected(conex.rs.getBoolean("relatorios"));
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Erro ao selecionar os dados!\n" + ex.getMessage());
            }
            conex.desconecta();
            jTextFieldLogin.setEnabled(true);
            jTextFieldNome.setEnabled(true);
            jPasswordFieldSenha.setEnabled(true);
            jPasswordFieldConfSenha.setEnabled(true);
            jCheckBoxCadLogins.setEnabled(true);
            jCheckBoxCadCat.setEnabled(true);
            jCheckBoxCadClientes.setEnabled(true);
            jCheckBoxCadForn.setEnabled(true);
            jCheckBoxCadProd.setEnabled(true);
            jCheckBoxPesqVendas.setEnabled(true);
            jCheckBoxVendas.setEnabled(true);
            jCheckBoxRelatorios.setEnabled(true);
            jButtonNovo.setEnabled(false);
            jButtonSalvar.setEnabled(true);
            jButtonExcluir.setEnabled(true);
            jButtonCancelar.setEnabled(true);
        }
    }//GEN-LAST:event_tabelaMouseClicked

    private void preencherTabela(String sql) {
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"Nome", "Login"};
        int i = 0;
        conex.conexao();
        conex.executaSQL(sql);
        try {
            conex.rs.first();
            do {
                i++;
                dados.add(new Object[]{conex.rs.getString("nome"), conex.rs.getString("login")});
            } while (conex.rs.next());
        } catch (SQLException ex) {
            //JOptionPane.showMessageDialog(this, "Erro ao preencher Arraylist!\n"+ex.getMessage());
        }

        ModeloTabela modelotabela = new ModeloTabela(dados, colunas);
        tabela.setModel(modelotabela);
        if (i > 5) {
            tabela.getColumnModel().getColumn(0).setPreferredWidth(259);
            tabela.getColumnModel().getColumn(1).setPreferredWidth(259);
        } else {
            tabela.getColumnModel().getColumn(0).setPreferredWidth(267);
            tabela.getColumnModel().getColumn(1).setPreferredWidth(266);
        }
        tabela.getColumnModel().getColumn(0).setResizable(false);
        tabela.getColumnModel().getColumn(1).setResizable(false);
        tabela.getTableHeader().setReorderingAllowed(false);
        tabela.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tabela.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        conex.desconecta();
    }

    private void estadoInicial() {
        flag = 0;
        jTextFieldLogin.setText("");
        jTextFieldNome.setText("");
        jPasswordFieldSenha.setText("");
        jPasswordFieldConfSenha.setText("");
        jButtonSalvar.setEnabled(!true);
        jButtonCancelar.setEnabled(!true);
        jTextFieldLogin.setEnabled(!true);
        jTextFieldNome.setEnabled(!true);
        jPasswordFieldSenha.setEnabled(!true);
        jPasswordFieldConfSenha.setEnabled(!true);
        jButtonNovo.setEnabled(!false);
        jButtonExcluir.setEnabled(false);
        jCheckBoxCadLogins.setSelected(false);
        jCheckBoxCadCat.setSelected(false);
        jCheckBoxCadClientes.setSelected(false);
        jCheckBoxCadForn.setSelected(false);
        jCheckBoxCadProd.setSelected(false);
        jCheckBoxPesqVendas.setSelected(false);
        jCheckBoxVendas.setSelected(false);
        jCheckBoxRelatorios.setSelected(false);
        jCheckBoxCadLogins.setEnabled(false);
        jCheckBoxCadCat.setEnabled(false);
        jCheckBoxCadClientes.setEnabled(false);
        jCheckBoxCadForn.setEnabled(false);
        jCheckBoxCadProd.setEnabled(false);
        jCheckBoxPesqVendas.setEnabled(false);
        jCheckBoxVendas.setEnabled(false);
        jCheckBoxRelatorios.setEnabled(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Usuario().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JCheckBox jCheckBoxCadCat;
    private javax.swing.JCheckBox jCheckBoxCadClientes;
    private javax.swing.JCheckBox jCheckBoxCadForn;
    private javax.swing.JCheckBox jCheckBoxCadLogins;
    private javax.swing.JCheckBox jCheckBoxCadProd;
    private javax.swing.JCheckBox jCheckBoxPesqVendas;
    private javax.swing.JCheckBox jCheckBoxRelatorios;
    private javax.swing.JCheckBox jCheckBoxVendas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel;
    private javax.swing.JPasswordField jPasswordFieldConfSenha;
    private javax.swing.JPasswordField jPasswordFieldSenha;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldLogin;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldPesqUsu;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
